### ISSUE TITLE
tweet text info not showing below tweet image popup

### ISSUE THREAD

**Issue by madLyfe** [MehediH/Tweeten#1]
![r0gsbfo](https://cloud.githubusercontent.com/assets/16073360/13901318/a1cdfa0a-eded-11e5-8abb-eac88e689d99.png)

**Comment by MehediH** [comment]
That's by design. We wanted to keep the media viewer clean.

**Comment by madLyfe** [comment]
understandable. it makes it hard to know image context especially if the tweet is trying to explain something rather than just an image header for a link.
