### ISSUE TITLE
the setting "Minimize to tray on close" does not work (Tweeten 2 on Windows 7)

### ISSUE THREAD

**Issue by lastsamurai26** [MehediH/Tweeten#1]
the setting "Minimize to tray on close" does not work without the setting "show app on tray" !!

Is this intended or a bug?

**Comment by MehediH** [comment]
Did you restart the app after setting Minimize Tray?

**Comment by lastsamurai26** [comment]
Yes, I made a restart of Tweeten after changing the settings.

In the task manager I can see the tweeten processes but an icon does not appear in the tray

**Comment by MehediH** [comment]
Disable "Show app on Tray", enable Minimize To Tray, close the app, open it again. The tray icon should show up -- make sure to check the collapsed taskbar area, too.

**Comment by lastsamurai26** [comment]
doesn't work 

I disabled "Show app on Tray" and enabled "minimize to tray"
After a complete of tweeten and PC restart , still no icon appeared

Only when I activate both settings it works

sry :-/

**Comment by MehediH** [comment]
Will check when I'm on Windows, thanks.

**Comment by lastsamurai26** [comment]
no problem :)

**Comment by lastsamurai26** [comment]
I have tested this again under Windows 10, there is also the problem

**Comment by MehediH** [comment]
Fixed in 4.0.1.
