### ISSUE TITLE
Merging multiple columns together

### ISSUE THREAD

**Issue by Mohamed3on** [MehediH/Tweeten#10]
Hi. I'm wondering if it is possible to merge two columns together, say a search column + a list column?
Something that's similar to [Rx's merge](http://reactivex.io/documentation/operators/merge.html).

**Comment by MehediH** [comment]
Not possible

**Comment by Mohamed3on** [comment]
Can you please elaborate on why?

**Comment by MehediH** [comment]
Tweeten works over TweetDeck which means we don't have the power to actually manipulate the app to show content from multiple columns in one single column. We could theoretically do it with some JavaScript, but that's a very hack-y solution and won't be viable.

**Comment by Mohamed3on** [comment]
Got it. I thought it was actually separate from TweetDeck and could interact directly with Twitter APIs. Thanks!

**Comment by MehediH** [comment]
Not a problem.
