### ISSUE TITLE
Maximize window broken

### ISSUE THREAD

**Issue by Blackwolfe5** [MehediH/Tweeten#101]
Lately I have been getting a very annoying problem with Tweeten. The maximize window button on the top right has dissapeared. Furthermore the default mode overlaps and hides the taskbar. (is fullscreen default?

Also, when minimizing Tweeten and then opening it again I get this error message 
![2018-06-28 23_18_25-window](https://user-images.githubusercontent.com/40699677/42105545-f4cf4592-7bd0-11e8-9bed-b99aaa5924cf.jpg)

I can press F11 to temporarily fix it but then when minimizing and then bringing up tweeten the "maximized" window is smaller. 

This being on Windows 10 (x64) build 17134. (The issues seemed to start after I updated to that build)

**Comment by MehediH** [comment]
Could you please backup your settings and send the content here? Also could you tell me exactly what you do after starting the app that takes you to this error?

**Comment by Blackwolfe5** [comment]
1. Minimize the app.
2. Click on Tweeten in the system tray.
3. Error appears.

Actually it seems to happen even if Tweeten isn't minimized. Happens every time I click on the tweeten icon in the system tray.

[tweetenback.zip](https://github.com/MehediH/Tweeten/files/2151034/tweetenback.zip)

**Comment by MehediH** [comment]
Couldn't repro it on my system. Could you please try deleting the Tweeten folder from %appdata%?

**Comment by MehediH** [comment]
Thanks!
