### ISSUE TITLE
Preparing for jQuery move to module scope

### ISSUE THREAD

**Issue by pixeldesu** [MehediH/Tweeten#102]
As you might have already heard, TweetDeck is planning to move global jQuery (and lodash) from `window.$/jQuery` into the Webpack module scope to easier work with it.

This will most certainly break a lot of userscripts and applications that utilize it and I'm pretty sure yours is not an exception to this.

You can include jQuery yourself, issue being, if you actually use events from TweetDeck, you won't be able to access them, as their data is not shared across multiple instances on the same page.

You'd need to access TD's module jQuery to get events and their data back, and there is no easy way to do that without any extra help.

The extra help is a module I developed called [moduleRaid](https://github.com/pixeldesu/moduleRaid). It takes the Webpack instance on a website and gives developers the ability to use all..or most modules available.

I'm not going too much into instructions on how to use it, but this is a snippet that will return jQuery back to where it was. _You of course need to run this in the script that is injected into TweetDeck for it to actually do something!_

```js
window.$ = mR.findFunction('jQuery')[1]
```

At least that was where I found jQuery to be in the module search.

That's everything. _Just not going to let Tweeten die from the upcoming change! :P_

**Comment by MehediH** [comment]
Hey Andy, thanks for the heads-up. I already worked with the creator of BTD to fix the Tweeten desktop app but since the Chrome extension is a regular extension there is no way of including node modules so I will have to look into fixing that some other way. Any ideas?

**Comment by pixeldesu** [comment]
You can just include the script in your application somehow, copy-paste it in or so, it has no dependencies whatsoever.

The node module is just there to make it easier to work with in a node development environment. So you can just `require` it and compile it down using toolchains or whatever.

**Comment by MehediH** [comment]
Aha. Thanks a lot. Will work on an update tomorrow and roll it out on Monday. Let's hope it works out.

**Comment by pixeldesu** [comment]
@MehediH It broke, module order changed and I needed to improve the search to only return a single object

switch above moduleRaid statement with `mR.findFunction("jquery:")[0]` and it should fix it.

**Comment by MehediH** [comment]
All platforms have been updated with the latest fix. Thanks a ton :)
