### ISSUE TITLE
Two-Factor Authentication, no different verification possible

### ISSUE THREAD

**Issue by schenklklopfer** [MehediH/Tweeten#103]
Logging in to TweetDeck without Tweeten allows to change to a different verification method.  
From Code Generator App to SMS or the other way.

Look at the picture, left side Tweeten, right side TweetDeck:
![image](https://user-images.githubusercontent.com/6595165/42133183-ba55af9a-7d25-11e8-8501-a9c52e3bbf99.png)

**Comment by MehediH** [comment]
This should be possible with the new Tweeten 4.5.

**Comment by schenklklopfer** [comment]
Sorry, but it still doesn't work.
Upgraded to Tweeten 4.6 already and also tried to delete my Tweeten Folder in %appdata%.
Still doesn't work.
