### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by MoZi1** [MehediH/Tweeten#109]
So, when starting Tweeten the first issue is that it's in full Fullscreen and not in a window. When i close Tweeten and have minimize to tray enabled, then opening it back from the tray it gives the following error: 
![image](https://user-images.githubusercontent.com/40969160/42470118-da6d3100-83b9-11e8-8a36-c7cffac2f46a.png)

This won't crash Tweeten and when i press Ok i can still use it, but the window cant be made smaller either with this button: 
![image](https://user-images.githubusercontent.com/40969160/42470189-03648126-83ba-11e8-81af-5cad267ad721.png)
Like, when pressing it, nothing happens and Tweeten is in constant Fullscreen and therefore annoying to use. Sometimes the whole button disappears too: 
![image](https://user-images.githubusercontent.com/40969160/42470234-2c82f6dc-83ba-11e8-8ebc-8abb13b02269.png)

**Comment by BradyThe** [comment]
Side note to the fullscreen problem: You can toggle Fullscreen with the F11 key.

**Comment by MehediH** [comment]
Hey guys, this is fixed on 4.6.4. And there's a new button to exit the full-screen mode on the titlebar.
