### ISSUE TITLE
[BUG] Mac OS X Version: App Icon not showing

### ISSUE THREAD

**Issue by andipalmer** [MehediH/Tweeten#11]
Hey there, I just wanted to report a quick bug I noticed in the latest version. The app icon is not showing for me on Mac OS X 10.11.3
Here's a screenshot: [https://monosnap.com/file/xKS1iUjbD1RmaeUGafOjnBJi3X5H67](https://monosnap.com/file/xKS1iUjbD1RmaeUGafOjnBJi3X5H67)

**Comment by davort** [comment]
I noticed it wasn't showing for me when using my Thunderbolt 27" screen, but shows up nicely when viewing on my MBP's screen.

**Comment by MehediH** [comment]
Fixed with Tweeten 1.9 - tweeten.xyz/osx
