### ISSUE TITLE
Can't download the firefox extension

### ISSUE THREAD

**Issue by newzorensia** [MehediH/Tweeten#111]
I have access the website to download the firefox extension of tweeten but when I click at the button it displayed as not found the extension 

What should I do for download it or can it be back?

**Comment by Nehemoth** [comment]
Please, I would like the return of the firefox extension too

**Comment by MehediH** [comment]
Firefox reviewers are too fussy about the code and I don't have the time to make changes to the extension for it to get approved by the Firefox team. Thus I have temporarily pulled the FF extension.
