### ISSUE TITLE
Problems with newest releases (4.5.2/3) on OSX

### ISSUE THREAD

**Issue by codingmimi** [MehediH/Tweeten#112]
I'm unable to run the newest releases (update necessary to protect against latest TweetDeck update) on my OSX (10.10.5) system. Before there was no problem with it. Error caused by: 
Dyld Error Message:
  Symbol not found: _CIDetectorTypeText

**Comment by MehediH** [comment]
Please try newer versions of macOS.

**Comment by MehediH** [comment]
Please try out 4.6.0. The issue should be fixed
