### ISSUE TITLE
No abillity to add multiple accounts

### ISSUE THREAD

**Issue by cj1987** [MehediH/Tweeten#115]
When I click the 'accounts' tab, I am unable to add my websites profiles which is a huge set back. I have used this in the past successfully but upgrading seems to have wiped everything and I had to re-sign into Twitter. There's options for others to manage my account, but I can't add a secondary or third account for some reason.

**Comment by cj1987** [comment]
I just logged into Tweetdeck, I have the ability to add additional accounts there - I will use that until Tweeten adds the 'Link another account you own' option to the account tab.

**Comment by MehediH** [comment]
This option exists on TWeeten as well: 
![image](https://user-images.githubusercontent.com/10274434/43045863-2c0820e4-8db8-11e8-92ee-980c814846ea.png)
