### ISSUE TITLE
Desktop Bridge version throws EPERM when enabling Tweeten Black

### ISSUE THREAD

**Issue by mkrautz** [MehediH/Tweeten#117]
The version of Tweeten from the Windows Store gives me this error just after installing, logging in, and clicking "ENABLE TWEETEN BLACK".

The error dialog is modal, so the app is unresponsive. When I dismiss it via clicking OK or [X], it comes right back up.

![desktopbridge-tweeten-eperm](https://user-images.githubusercontent.com/36527/43689213-286cd232-98f7-11e8-9741-cd9113fc1224.png)

**Comment by mkrautz** [comment]
After closing Tweeten, and re-opening it, black mode is enabled, and the app works as expected so far.

**Comment by MehediH** [comment]
This is probably a limitation on the UWP platform so I wasn't able to detect the bug when testing the update. But as you said, restarting the app should fix it
