### ISSUE TITLE
Is the source code for this app available?

### ISSUE THREAD

**Issue by ClairelyClaire** [MehediH/Tweeten#120]
...or is this GitHub repo just for the Tweeten website?

**Comment by MehediH** [comment]
It’s not but if you have any ideas feel free to let me know

**Comment by ClairelyClaire** [comment]
I'm trying to understand how you're getting the full responses to a tweet, but I've since realized that this is just a wrapper for TweetDeck, which is probably using private APIs to accomplish this, since it's owned by Twitter.

**Comment by MehediH** [comment]
Yep.
