### ISSUE TITLE
Can not install update

### ISSUE THREAD

**Issue by snowbound** [MehediH/Tweeten#124]
On every start up of the app on Windows 7 x64 getting told that it could not install the update. Checking for updates I get "tweeten is having troubles downloading the update". Version is 4.6.1

**Comment by manderley3** [comment]
I have this issue also for the past good few weeks.  I am on Windows 10 x64.  Version 4.6.1

**Comment by manderley3** [comment]
Today I have done a clean re-install of Tweeten but the issue is still there.

**Comment by snowbound** [comment]
Has this software been abandoned? No response it seems to any of these issues for 3 months or so. I went back to Tweetdeck in my browser. That seems to be less resource demanding than TweetenApp. Sorry to say that.
