### ISSUE TITLE
There's no way to add a second account?

### ISSUE THREAD

**Issue by Trophonix** [MehediH/Tweeten#128]
I have quadruple checked every place in this UI that makes sense for there to be an "add account button" and I just can't find anything...

- Click "accounts" in the bottom left, brings up a sidebar with my first account listed
- Click the user account avatar in the bottom left, brings up stuff I can edit about this one account but no add options
- Tried going to send new tweet to see if there'd be a button next to the account avatar saying "tweet from another account"

Please make your UI less bad and also tell me how to add a new account...

**Comment by wires** [comment]
When I go to accounts, there is "Link another account that you own", but I cannot figure out how to add an account. Is that this bug?

Otherwise lovely program, thanks for making it available.

**Comment by tylerregas** [comment]
Tweetdeck, and Tweeten by extension, only support a single account. You add additional accounts by granting tweet rights to your primary user for the accounts you want to add. This isn't a bug, but a quirk of how Twitter set up Tweetdeck.

**Comment by Swaggadan** [comment]
How about having different instances of Tweeten that has different accounts? Similar to Telegram portable version.

**Comment by jesse9212** [comment]
> 
> 
> How about having different instances of Tweeten that has different accounts? Similar to Telegram portable version.

Is this possible to do?
