### ISSUE TITLE
Can't share collections

### ISSUE THREAD

**Issue by BobHarper1** [MehediH/Tweeten#129]
The only way to create a 'collection' is [through using TweetDeck](https://developer.twitter.com/en/docs/tweets/curate-a-collection/overview/overview.html).

This is fine, and possible to do when using with Tweeten. However, to share a collection you need to use the 'share > view on twitter' feature for the column which is available in TweetDeck (see image), but the user does not have the option when using Tweeten.

![image](https://user-images.githubusercontent.com/10833378/47363478-d29e5900-d6ce-11e8-80da-f5c87754eee4.png)

Particularly, collections are often created for using as embeds. This is only possible by using the TweetDeck embed feature, or by having the url, both of which are possible only through the feature in TweetDeck.

**Comment by MehediH** [comment]
This is fixed on 4.6.4. Thanks!
