### ISSUE TITLE
Feature Request: Clear column, visible without further clicking

### ISSUE THREAD

**Issue by janpio** [MehediH/Tweeten#13]
Button to clear a column as read next to current "..." button in header.

**Comment by MehediH** [comment]
If you scroll to the top of the column it automatically makes column as read

**Comment by janpio** [comment]
Yes, but that is not what I want. I want to be able to click "Clear" when I read all of a column (or just don't want to see these tweets any more) without having to open the "options" for reach column manually. 

For Chrome this userscript exists: https://greasyfork.org/de/scripts/15976-tweetdeck-clear
