### ISSUE TITLE
Do the hot-fixes still update even though Tweeten for the past numerous months on start up says it can not update?

### ISSUE THREAD

**Issue by manderley3** [MehediH/Tweeten#134]
Do the hot-fixes still update even though Tweeten for the past numerous months on start up says it can not update?

**Comment by MehediH** [comment]
No, you have to be one one of the latest updates for the hotfix to work. We can't build hotfixes that work consistently across older versions, so the hotfixes are only built and test for the recent releases.

**Comment by manderley3** [comment]
I am on 4.6.1
