### ISSUE TITLE
Can't use Tweeten after last update.

### ISSUE THREAD

**Issue by XSilverlink** [MehediH/Tweeten#139]
Hey, 

Love your app. But since the last update i can't use the app anymore. Whatever I click  (Getting Started or create account) there is nothing happening. Uninstalled the app and cleared everything in %LocalAppdata% and %Appdata%. It doesn't work.

**Comment by MehediH** [comment]
Hey, could you download an older version of the app (4.6.2) https://github.com/MehediH/Tweeten/releases/tag/v4.6.2 login, and upgrade to 4.6.6 and see if the issue persists?

**Comment by XSilverlink** [comment]
Installed 4.6.2. Successfully logged in.
Update prompt came. Installed update. Can't login again.

**Comment by XSilverlink** [comment]
It seems when the "Christmas" theme is enabled it become unusable.

**Comment by XSilverlink** [comment]
It kinda sucks to reinstall every time i update a setting and the update notification can't be turned off either.
