### ISSUE TITLE
Font clashes with background color when adding users to lists

### ISSUE THREAD

**Issue by mrwhatley** [MehediH/Tweeten#14]
![tweetenlist](https://cloud.githubusercontent.com/assets/18123997/14086317/87291f5c-f4f2-11e5-820c-8d3753692649.png)

Requesting that the fonts associated with a Tweeten user's Twitter lists are lighter, so that they are easier to read

**Comment by MehediH** [comment]
Fixed with Tweeten 1.8!

Windows: tweeten.xyz/windows
OS X: tweeten.xyz/osx
