### ISSUE TITLE
A few ideas for improvement...

### ISSUE THREAD

**Issue by umbrageous** [MehediH/Tweeten#143]
1) Could the dark blue bar at the top be narrower, so as to save screen real estate?

2) The bar's dark color makes the Tweetdeck semi-circle new tweet indicator impossible to see. Could it be lightened?

3) Would it be possible to R-click and open a tweet in the default browser?

Thanks.

**Comment by BradyThe** [comment]
>3. Would it be possible to R-click and open a tweet in the default browser?

Opening tweets in the browser is already possible. To do that simply click on the tweet timestamp.
![MYCkcPiV5tPtl8KGlQdV](https://user-images.githubusercontent.com/8181555/56461735-f0b3f000-63b7-11e9-98b3-b35196f93e0e.png)

**Comment by Poilaucul** [comment]
It would be great if tweets timestamps could be set to absolute/relative time.
Absolute time is easier to track when you have to catchup on tweets that are days old.
