### ISSUE TITLE
Emoji picker and GIF search not appearing even in latest update

### ISSUE THREAD

**Issue by ratchetchan** [MehediH/Tweeten#145]
As the title says, the features that the last update was apparently solely created to restore do not appear for me. I have uninstalled and reinstalled. I installed the last version I know to have contained them (with the holiday theme) and as soon as it opened, I saw the features there, but then the application **_immediately_** updated and they were gone again. I'm totally lost here. I sent a tweet, but I know the developer is busy with school. Should I use Better Tweetdeck in the meantime?

**Comment by burdoto** [comment]
I have found details to this, when I noticed the Emoji Board randomly showing up:
https://twitter.com/Kaleidox_/status/1260954121202532353

Steps to reproduce:
- Open "New Tweet" dialogue
- Activate "Stay Open" in the bottom to always have the "New Tweet" activity stay open
- Reload using [CTRL+R] or restart Tweeten
- The "New Tweet" dialogue will be open, but the emoji board should be missing
Here comes the fix:
- Close the New Tweet dialogue
- Reopen the New Tweet dialogue
- Select another account
- The Emoji board should now be back
