### ISSUE TITLE
I can't close the composer and the button bar on the left is a little mixed up.

### ISSUE THREAD

**Issue by Amonshi284** [MehediH/Tweeten#146]
![Tweeten](https://user-images.githubusercontent.com/16608842/57916297-d5db7b00-7892-11e9-9b6d-d22ebdc85b8e.PNG)

**Comment by nykoo** [comment]
same here, alternative i found time for @MehediH to fix tweeten since last tweetDexk update is to switch to account and then you can close the panel
![Annotation 2019-05-19 151436](https://user-images.githubusercontent.com/8900539/57982679-e6cded00-7a48-11e9-9d3d-97c5f971c75c.jpg)

**Comment by Amonshi284** [comment]
Todays update fixed it for me.
