### ISSUE TITLE
Drag and drop bug

### ISSUE THREAD

**Issue by Atoile** [MehediH/Tweeten#15]
When trying to drag and drop some pictures, sometimes it just opens it in full and throws this error
![tweeten_2016-03-29_10-48-27](https://cloud.githubusercontent.com/assets/3499652/14099138/23ba0b48-f59c-11e5-9aef-18bf4e210b1a.png)
After that, tweeten is nearly impossible to close even with Task manager

**Comment by MehediH** [comment]
What version of Tweeten are you using?

**Comment by Atoile** [comment]
Latest one, it just updated today - 0.1.160328-1500
Also it seems like this only affects pics made with ShareX

**Comment by MehediH** [comment]
Thanks, will fix.

**Comment by MehediH** [comment]
Fixed with Tweeten 1.8!

Windows: tweeten.xyz/windows
OS X: tweeten.xyz/osx
