### ISSUE TITLE
"Couldn't install the patch" 

### ISSUE THREAD

**Issue by gabyblech** [MehediH/Tweeten#156]
Keep getting this error, and needing to sign in every time, it doesn't save my login details

**Comment by dangeredwolf** [comment]
Tweeten is currently broken on macOS... who knows when this will be fixed. It's a really simple thing actually, they forgot to upload the latest-mac.yml file with the release last July 2019. This has broken auto-updates, unfortunately. As of now, this means using an alternative like Twitter Web, stock TweetDeck, ModernDeck or the like.

**Comment by MehediH** [comment]
Have some issues with my Apple Developer account that I am trying to get fixed asap, but need Apple to reply. Will fix soon, though.
