### ISSUE TITLE
How to display more information in one column?

### ISSUE THREAD

**Issue by michaelfresco** [MehediH/Tweeten#157]
When I compare TweetDeck with Tweeten, I notice that I see more tweets on TweetDeck. Is there a setting to reduce the amount of white-space under the Tweets so the timeline becomes a bit more compact?

See screenshot here for side by side comparison:

https://i.imgur.com/LwQYNvo.png

**Comment by michaelfresco** [comment]
I see I can just fiddle with the CSS, so I can fix this. Closing now

**Comment by elvissey1984** [comment]
> I see I can just fiddle with the CSS, so I can fix this. Closing now

Hi Michael - exact same complaint but not as advanced on web programming...

can you please share how you fix this with the CSS? Thanks a lot
