### ISSUE TITLE
High CPU usage recently

### ISSUE THREAD

**Issue by shihofuyu** [MehediH/Tweeten#158]
Hi, I noticed that for the last 1-2 weeks, Tweeten is always using around 20-40% CPU on my PC no matter what I do on it or just idling. Tweeten's performance is the same as always and I don't really feel any impact using my PC either but needless to say, this is out of the ordinary and it never did this before. Don't have this problem on any of my other devices that have Tweeten running so not sure if the problem is on my PC's end. I tried a fresh install, trying with hardware accel on/off, no change. I thought maybe reducing my number of columns (10 right now) would do something but it didn't.

What can I do?

**Comment by jpwester** [comment]
I am experiencing the same thing over roughly the same time period. This is still occurring for me today.

**Comment by Nigh7Stalk3r** [comment]
Same for me, it's using 15-20% constantly.

**Comment by azumukupoe** [comment]
same
