### ISSUE TITLE
Dragging images to post on tweets will cause an uncaught exception and leave the app hanging

### ISSUE THREAD

**Issue by Finnishguy101** [MehediH/Tweeten#16]
Title says it all. Tried to drag and drop an image to post on a tweet because I'm used to it from Tweetdeck. Tweeten apparently doesn't really like that and decides to open the picture in the app itself. (Possible feature request there: drag&drop w/ images.)

This results in a horrible crash. I tried re-creating the crash with another instance, and the results varied slightly. The first crash left a process that I can't terminate from the task manager. The second crash didn't, and terminated successfully.

Attached an image with the error. Hopefully you can fix it soon.

OS is Windows 7, if that was unclear (doubt that it was, but better be safe than sorry I guess.)
![untitled1](https://cloud.githubusercontent.com/assets/18250535/14234967/1f628c80-f9f9-11e5-8f25-d86a8428ea95.png)

(I'm bad at explaining things, but hopefully this is fine.)

**Comment by MehediH** [comment]
Are you using the latest update? I have fixed this issue in 1.8.

**Comment by Finnishguy101** [comment]
Rebooted to clean the process, restarted Tweeten and apparently there was an update which fixes this very same problem. Is this a recent one? I don't recall seeing the update dialogue when I booted up my PC yesterday.
Anyway, I'm clearing this topic since the problem has been fixed.

**Comment by MehediH** [comment]
Yes, we released it this afternoon.

**Comment by Finnishguy101** [comment]
I see, thanks for the help.

**Comment by MehediH** [comment]
(if you wanna check for updates, just right-click anywhere in the app and click on check for updates)

**Comment by Finnishguy101** [comment]
Oh, didn't know that. Thanks for the tip.
