### ISSUE TITLE
Tweeten 5.x has a number of scaling issues with nonstandard Windows DPI settings

### ISSUE THREAD

**Issue by axfelix** [MehediH/Tweeten#162]
I'm sure this is due to an Electron upgrade, as I know some other Electron apps I use have become DPI-aware after recent updates, but most of them can be made to behave normally by using the regular zoom in/zoom out settings. Tweeten looks fine to me after a single zoom out (I mostly use the Windows DPI settings to correct the look of Explorer, which doesn't support zooming and is quite small on modern monitors otherwise), but it has a few other weird edge cases here:

- The window can only be shrunk horizontally to slightly longer than whatever column width I set. I'd had Tweeten set to ~376px per column and was using the window that wide so it was effectively a one-column-at-a-time-app, for which it worked great; now it looks like this, and growing the columns also seems to grow the minimum window width.

![image](https://user-images.githubusercontent.com/252047/74352505-79e44b00-4d6d-11ea-8e65-8919a8c6f849.png)

- The saved window size seems to grow slightly every time I close and open the app, and I have to shrink it down again. It looks like this is growing by exactly 110% which is what I use for my Windows scaling so I strongly suspect these are related, but I haven't seen this bug in other Electron apps I use regularly (Signal, Spotify) so I think it has to be fixable.

Thanks!

**Comment by axfelix** [comment]
Also, the jumping new tweet icon that was fixed in the last 4.x release is back:

![image](https://user-images.githubusercontent.com/252047/74352720-c7f94e80-4d6d-11ea-92ef-84d2f9f16fe4.png)

**Comment by axfelix** [comment]
I think the most straightforward way to fix this, rather than having to handle zoom in all kinds of different ways, would be:

- lower the minimum window width to something very small (I don't think tying it to zoom level will be easy to enforce)
- use Signal's methods for saving window size as they don't seem to be affected by zoom level or DPI settings: https://github.com/signalapp/Signal-Desktop/blob/development/main.js#L295

**Comment by MehediH** [comment]
Hi, I have addressed the issue with the search icon jumping, and also fixed some issues with multi-monitor behaviour.

But I am still struggling to fix the issue with the window automatically expanding when scaling is not set to 100%. I am saving Tweeten's window state just like Signal, and restoring them whenever the user launches the app, but still for some reason the window automatically expands by the scale factor of the display. 

If you have any idea what could be going wrong, feel free to share :) I will keep investigating in the meantime.

**Comment by axfelix** [comment]
At least you're able to duplicate! I'll see if I can find anything.

**Comment by MehediH** [comment]
Ok so the issue seems to be with `minWidth` on the `BrowserWindow`. It automatically expands the window if a `minWidth` is set, but else it doesn't and restores to the actual size from the last saved state.

**Comment by MehediH** [comment]
@axfelix I just sent you a test build with the DPI fixes on Skype, if you wanna give it a try

**Comment by axfelix** [comment]
Would you mind just pushing this to the regular release channel? I had weird Electron auto-update issues with the test build.

**Comment by axfelix** [comment]
Doesn't look like this fix made it into 5.0.3...

**Comment by MehediH** [comment]
Yeah, I am still investigating this. There are a number of DPI-related issues in Electron and Chromium that's making things harder. What issues are you experiencing in 5.0.3?

**Comment by axfelix** [comment]
Mostly the one where it's resized every time I close and open the app.

**Comment by MehediH** [comment]
@axfelix I shared a new build with you on Skype, check it out and let me know if that improves anything

**Comment by MehediH** [comment]
This has been addressed over the last couple of releases.
