### ISSUE TITLE
5.0.2 Crash after clicking Get Started

### ISSUE THREAD

**Issue by mscrivo** [MehediH/Tweeten#164]
I've been a long time happy user, but after the 5.0.2 update, I've been unable to launch Tweeten at all.  It crashes every time I click "Get Started" as soon as the twitter login screen appears.  I've attached the exception analysis from WinDbg if it helps any.  I can also send you full mem dump if you need.
[exception analysis.txt](https://github.com/MehediH/Tweeten/files/4219743/exception.analysis.txt)

**Comment by fear025** [comment]
I am also experiencing this problem on WIndows 10. It's "fixed" by uninstalling, and then reinstalling the previous version (4.7), and turning off "Enable auto updates" and "Enable automatic hot fixes", but the upgrade notification is pretty annoying.

**Comment by fear025** [comment]
Thanks for fixing this, confirmed that 5.0.5 is working great!
