### ISSUE TITLE
Allow resizing freely

### ISSUE THREAD

**Issue by ronilaukkarinen** [MehediH/Tweeten#167]
Hello! I see I cannot resize under column. I'd like to decide how narrow the window is. Column size can be resized in settings, but minimum window size is pre-defined? I want to resize the window even smaller than column to hide the scrollbar (as in Tweetbot).

**Comment by Gubith** [comment]
"too narrow" is fine, in case someone has super small fonts or something.

**Comment by ronilaukkarinen** [comment]
I'm not sure if I understand your comment. I mean on macOS I canNOT make the window narrower than 1 column. Why is that?

**Comment by MehediH** [comment]
That is by design, so that you can always at least see one column
