### ISSUE TITLE
Save Changes wont close on no

### ISSUE THREAD

**Issue by Gubith** [MehediH/Tweeten#168]
The dialog "Save settings?" is not closing when I click Yes or No.

I actually didn't make any changes,  I checked and unchecked something.

To exit settings I had to save changes.  

W10, 
Tweeten 5.0.2

**Comment by jrmain** [comment]
Same here. The only way to exit from the Settings dialog is to click the Save button, which also restarts Tweeten. Windows 8.1 64 bit.

**Comment by jrmain** [comment]
Does the fact that this issue was closed mean that it has been fixed?

**Comment by MehediH** [comment]
Yep this will be fixed in the next version..should be out tomorrow.
