### ISSUE TITLE
Tray functionality broken on Win 8.1

### ISSUE THREAD

**Issue by wimg** [MehediH/Tweeten#169]
When selecting 'show app on tray' or 'minimize on close', as soon as I click 'Save Settings', Tweeten restarts and shows an error box :
![image](https://user-images.githubusercontent.com/313511/78061804-0da9bf00-738e-11ea-8079-7d883076594f.png)

Tweeten still starts after that, but it will not minimize to the tray or show the icon on the tray.

Environment is Windows 8.1 (64bit)

**Comment by alvgalrus** [comment]
I'm having this issue at the moment, Windows 10 x64 v1909. In my case it doesn't start after acepting the dialog...

**Comment by wimg** [comment]
Sadly this problem is actually not solved yet on Windows 8.1

**Comment by MehediH** [comment]
What version are you running @wimg?

**Comment by wimg** [comment]
I just updated to 5.0.5.
Now when I have either one of the options enabled, Tweeten will go beyond the startup screen.
When I close it and restart, I have to log in to my account again.
I've already tried uninstalling.

**Comment by MehediH** [comment]
I would suggest deleting the Tweeten folder from %appdata% and logging in again. Should fix it.

**Comment by wimg** [comment]
I uninstalled, deleted the Tweeten folder from %appdata%, reinstalled and logged in.
Then selected the Minimize to tray and Show app on try. As soon as I click save, it restarts and gives the error above.

**Comment by MehediH** [comment]
Could you please show me the error again? And can you verify you are running 5.0.5 from settings?

**Comment by wimg** [comment]
![image](https://user-images.githubusercontent.com/313511/86650438-fd375f00-bfe2-11ea-9b81-5466967015f6.png)
![image](https://user-images.githubusercontent.com/313511/86650453-ff99b900-bfe2-11ea-9f8d-e0731bd7df1b.png)

**Comment by MehediH** [comment]
That is very odd, I will look into this but can not promise a solution as Windows 10 is the only officially supported version of Windows. Thank you for the details!

**Comment by wimg** [comment]
Thanks for your effort. Happy to sponsor you for your hard work :-)

**Comment by MehediH** [comment]
Thank you! Appreciate it :)

**Comment by MehediH** [comment]
Hey @wimg, is this issue still occurring for you?

**Comment by wimg** [comment]
Hi @MehediH I'm happy to report this problem has been fixed in the new release :-D

**Comment by MehediH** [comment]
Great!

**Comment by wimg** [comment]
Sadly the app icon doesn't appear in the tray since the last update :-(

**Comment by MehediH** [comment]
Hmm, this is probably to do with Windows icon cache. I would suggest resetting the Windows icon cache for the tray icon to show up properly. It works fine here and I have not touched the tray functionality in a while :)

**Comment by wimg** [comment]
Sadly it doesn't fix it.
And the problem also occurs on my old laptop with Windows 7.

**Comment by MehediH** [comment]
Weird, have you tried uninstalling the app and reinstalling it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wimg** [comment]
Sadly no joy after an uninstall (even used IObit Uninstaller to remove all traces) and reinstall. The app runs in the background, but there's no icon anywhere to open it.

**Comment by MehediH** [comment]
That is odd, it works fine for me in Windows 10 and 11. Unfortunately as Tweeten only supports Windows 10 and higher, I am afraid I can't provide much help here :(
