### ISSUE TITLE
[Feature Request] allow even slimmer columns

### ISSUE THREAD

**Issue by lashman1985** [MehediH/Tweeten#17]
i recently installed Tweeten and found out that the minimum column width for it is 300px whereas in the original TD it's 272px ... it doesn't sound like a big deal, but i've got a very specific screen setup and 300px per column is just too wide for me :( would it be possible to add a "super-slim" mode for columns? i wouldn't even mind "sacrificing" the visibility of column names if that's the reason why the minimum is 300px right now

**Comment by RheingoldRiver** [comment]
I have the exact same issue, and I'd love to have even narrower, down to 225-250 or so

**Comment by MehediH** [comment]
Added with Tweeten 1.9 - tweeten.xyz/windows
