### ISSUE TITLE
Mac version no longer has an icon

### ISSUE THREAD

**Issue by dnlx** [MehediH/Tweeten#17]
After the last update the Mac Version of Tweeten no longer has an Icon.
![bildschirmfoto 2017-07-02 um 20 53 57](https://user-images.githubusercontent.com/14241290/27772745-996dd720-5f68-11e7-9696-89da356128b5.jpg)

**Comment by NerdCowboy** [comment]
@dnlx is this still an issue? I noticed this too, but subsequent updates have restored it for me.
