### ISSUE TITLE
"Update download path when saved to a different location" doesn't

### ISSUE THREAD

**Issue by SturmB** [MehediH/Tweeten#172]
Tweeten version: 5.0.2
Windows version: 10 v1909

I selected the checkbox in `Settings > App > Downloads` that says "Update download path when saved to a different location". I figured that, by doing this, if I download an image from Tweeten to a different location other than the default (currently `%HOMEPATH%\Downloads`), all subsequent image downloads from Tweeten would use that new path to start from.

Unfortunately, this is not the case. **Every** image download, no matter what, opens the "Tweeten Image Downloader" dialog in `%HOMEPATH%\Downloads`. I have to manually navigate to my preferred location every time.

Yes, the default can be changed in Settings (although I haven't tested that function yet), but I would much prefer that Tweeten "remember" my last download folder.

**Comment by MehediH** [comment]
Hi! This has been fixed on the latest version, please download 5.0.3!

**Comment by SturmB** [comment]
Confirmed. It's working as expected now. 🎉 Thank you so much! 😊
