### ISSUE TITLE
The app is stuck in login modal

### ISSUE THREAD

**Issue by digijustin** [MehediH/Tweeten#175]
I just installed the 5.0.3 version and now the whole app is stuck in the login modal window. I have closed out the app and re-opened as well as uninstalled and reinstalled. I am on Windows 10 Pro version 1903 and using the Windows 64 bit installer
![Tweeten](https://user-images.githubusercontent.com/436009/82129503-3dfbc000-9778-11ea-8b69-5a7ea4a302da.PNG)

**Comment by MehediH** [comment]
When you saw the login form, what UI did you see? Was it identical to the following:
![image](https://user-images.githubusercontent.com/10274434/83194936-5a610a80-a131-11ea-9406-5ebedee55b75.png)

**Comment by digijustin** [comment]
Yes. I couldn't remember what the signin process looked like before but that is the exact thing I see. Then everything stays within that modal

**Comment by MehediH** [comment]
Should be fixed in 5.2.0
