### ISSUE TITLE
Mac 5.0.3 release broken

### ISSUE THREAD

**Issue by nekodex** [MehediH/Tweeten#176]
Hi there, just noticed that all the framework symlinks for the MacOS build seem to be broken:
![Screen Shot 2020-05-17 at 2 17 57 pm](https://user-images.githubusercontent.com/272140/82136499-a4044800-9849-11ea-8311-924bffb3e086.png)
(they're standard files instead of symlinks)

What they should look like:
![Screen Shot 2020-05-17 at 2 18 06 pm](https://user-images.githubusercontent.com/272140/82136501-a5ce0b80-9849-11ea-9696-2336705677cd.png)

Because of this the app won't run at all - I did confirm that manually fixing the symlinks allows the app to run... but you may want to double-check your build and/or packaging process. 😃

**Comment by MehediH** [comment]
Hey, what browser did you use to download the app?

**Comment by nekodex** [comment]
Safari 13.0.1 on MacOS 10.14.6

After a bit of digging, it looks like it may have to do with using [The Unarchiver](https://apps.apple.com/us/app/the-unarchiver/id425424353?mt=12) to extract the zip? Using the MacOS built-in `Archive Utility` to extract seems to create the symlinks correctly. Weird, as I've never seen `The Unarchiver` fail to create symlinks for an extracted `.app` before.

Even weirder is command-line `unzip` doesn't seem to like the archive either...
```
Archive:  tweeten-darwin-x64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

**Comment by MehediH** [comment]
Yeah, this is an issue in macOS, related to notarization: https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-544997415

Please use `ditto` to extract the zip. Just run `ditto -xk tweeten-darwin-x64.zip ." and that should work.
