### ISSUE TITLE
Windows 5.0.3 loses focus & cannot be accessed

### ISSUE THREAD

**Issue by korgano** [MehediH/Tweeten#177]
Windows 10 64bit - Home 1909
Tweeten standalone 5.0.3

After running Tweeten 5.0.3 for about 2 hours, I minimized the window and when trying to restore the window, the window would not return. Closing the application results in the program showing up in the Windows taskbar preview for a while, before the preview also disappears.

**Comment by MehediH** [comment]
Hi I couldn't reproduce this issue on my end, could you please share more details on this?

**Comment by MehediH** [comment]
Also could you share what settings you have enabled? Is your app set on the tray?

**Comment by korgano** [comment]
Here's my config.json settings - don't have anything in the log folder:
`{
	"lastWindowState": {
		"x": -32000,
		"y": -32000,
		"width": 697,
		"height": 728,
		"fullScreen": false,
		"aot": false,
		"maxState": false,
		"displayId": 2528732444
	},
	"accountHandler": {
		"accountStatus": "activated"
	},
	"customization": {
		"theme": "dark",
		"completeBlack": false,
		"font": "small",
		"columnWidth": 310,
		"roundAvi": true,
		"alwaysShowTweetActions": false,
		"hideDM": true,
		"thinSB": false,
		"showVB": false,
		"minimizeTray": false,
		"showTray": false,
		"emojis": true,
		"charCount": false,
		"profImagesOnNav": false
	},
	"autoUpdate": true,
	"hardwareAcc": false,
	"hotFix": true,
	"spellCheck": true,
	"TDSettings": {
		"linkShortener": {
			"toggle": true,
			"bitlyUsername": "",
			"bitlyApiKey": ""
		},
		"gifAutoplay": true,
		"gifZoom": true,
		"sensitiveData": true,
		"tweetStream": true
	},
	"macSettings": {
		"touchBar": true
	},
	"dev": {
		"mode": false,
		"customCSS": "",
		"backup": false
	},
	"downloadPathSync": false,
	"askSettings": false,
	"customTitlebar": false,
	"multipleInstances": false,
	"featureControl501": {
		"donation": 0,
		"feature": 0,
		"count": 4
	},
	"downloadPath": "C:\\Users\\____\\Downloads"
}`
