### ISSUE TITLE
[Feature Request] "Clear" button outside of column edit mode

### ISSUE THREAD

**Issue by lashman1985** [MehediH/Tweeten#18]
would it be possible to additionally (maybe as a toggle in settings or something) add the "Clear" column button outside of the column edit mode? the way i browse twitter right now is to catch up with the recent tweets and then clear the column so i know exactly which tweets are new ... the "problem" is - to get access to the "Clear" button i have to open the column edit rollout each time i want to do that ... and, as opposed to the Clear button, i don't really need all the other edit options (like filters etc.) to be visible at all times, but having the ability to just have the Clear button visible at all times (even under the column name) would be a great thing to have in Tweeten

**Comment by InTheMoment** [comment]
I want to second that request. It would be the most amazing feature and something I had been hoping for with the original TweetDeck forever. 

I use the "clear column" feature all the time don't need the other options of the filter dialogue on a regular base. So it is either 2 additional clicks with every clear (lots of unnecessary clicks and time) or it takes up a whole lot of screen real estate when leaving open. 

Having the "clear" button accessible outside of the filter dialogue would be such a great enhancement for Tweeten. 

PS: Thanks for providing such a great stand alone app for Windows. .)

**Comment by MehediH** [comment]
This isn't possible unfortunately, we will have to modify the actual TweetDeck JS, which we don't have access to.
