### ISSUE TITLE
request for new columns/UI perhaps? a row for 'following' linked to row of tweets from there linked to the thread/replies.

### ISSUE THREAD

**Issue by fortunewalla** [MehediH/Tweeten#182]
Not sure if your desktop app can be modified or extended for this but I am envisioning something like Outlook Desktop Email or an RSS reader.

First region consists of rows of accounts following. 
Second region consists of all rows of tweets from selected account.
Third region consists of entire thread/replies of selected tweet.

Leftmost column: instead of email boxes/RSS account name, we will have following accounts.
TopRight column: Instead of rows of emails/feed list, we have tweets list.
BottomRight column: Instead of email details or Feed preview, we have entire tweet thread with replies etc....
 
![image](https://user-images.githubusercontent.com/7158596/85384894-40172280-b55f-11ea-9e67-f1b44153f105.png)

I tried searching for such an app/web interface but didn't find anything like the above concept.

I feel it will be easy to casually browse one's own account this way.

Thanks

**Comment by MehediH** [comment]
Not possible, thank you.
