### ISSUE TITLE
Tweeten 5.0.4 won't save size & position

### ISSUE THREAD

**Issue by tehKD** [MehediH/Tweeten#183]
After i have installed 5.0.4 it won't save size and position anymore.
I've already tried to start the program with admin rights, but that did not help.

I'm using Windows 10 Home 2004 with the latest updates.

**Comment by MehediH** [comment]
Hey, can you try this build and see if the issue still persists? https://www.dropbox.com/t/9UQ1UNMAGrfJoryP

**Comment by tehKD** [comment]
Thank you for your response.
Unfortunatly this build has not resolved the issue.

**Comment by MehediH** [comment]
Could you please provide me with some more details, including steps to reproduce, and your monitor setup? Thanks

**Comment by MehediH** [comment]
Also please try this newer build https://www.dropbox.com/t/y34QLoF5j506oJuQ

**Comment by tehKD** [comment]
I open the program and resize it, Then i close it and when i restart it, it starts with the default size and position.
Im using two 2560x1440 monitors (Asus MG278 & PB277). I had no problems with previous versions.

I tried to install the build you linked but im getting this error message:
![tweeten_error](https://user-images.githubusercontent.com/54638643/86536462-1d362800-bee8-11ea-8881-e552ef10d4d7.jpg)

**Comment by MehediH** [comment]
Thanks, please try this out: https://www.dropbox.com/t/MYhdjjID3QeU2otT

**Comment by tehKD** [comment]
Success! It's working again :)

Thank you very much.

**Comment by MehediH** [comment]
Amazing, thank you!
