### ISSUE TITLE
Clicking (Left or Right) the bottom scrollbar opens the settings.

### ISSUE THREAD

**Issue by satsunyan** [MehediH/Tweeten#184]
I use Tweeten for multiple accounts so I scroll left and right often. Everytime I attempt that it opens the setting. I've tried installing an older version, restarting, and such. I'm not sure what's wrong. It wasn't like that until I changed the account I was using with it. Here's a gif of the odd bug: https://i.gyazo.com/939a0df2a4597304fea908466bb5b3c7.gif

**Comment by MehediH** [comment]
Hi this should be fixed in 5.0.5, please let me know if you still experience this.
