### ISSUE TITLE
Tweeten 5.0.5: Broken Mentions bar

### ISSUE THREAD

**Issue by tobimori** [MehediH/Tweeten#185]
![image](https://user-images.githubusercontent.com/29142128/86815665-33c4b680-c083-11ea-8a77-2364ce1d92af.png)

Mentions limited to a specific account instead of all work fine

**Comment by MehediH** [comment]
Works fine here. Need more details

**Comment by tobimori** [comment]
Anything you want me to specify on? 😅

**Comment by MehediH** [comment]
Ah, if it's happening on TweetDeck then its probably not specific to Tweeten. Still working fine here for the time being.

**Comment by tobimori** [comment]
Do you know anything I could try to maybe fix it?

**Comment by tobimori** [comment]
closed because it's a TweetDeck and not a Tweeten issue

**Comment by MehediH** [comment]
I would say just give it a few hours, if it still persists, let me know

**Comment by tobimori** [comment]
Still broken.
