### ISSUE TITLE
Clicking a trending topic moves the last column to the first

### ISSUE THREAD

**Issue by ILikeApps** [MehediH/Tweeten#186]
Hello! Whenever I click a trending topic, the last column on the right moves to the first/leftmost column. My setup would have the Trending column as the first one so, if let's say, the Messages column is the last one it moves to the first. This also happens when the Trending column is in between columns. Also as a test, I added a Trending column as the last column, the resulting search column was added as the first column. 

Both Microsoft Store and the 64-bit version has this problem on my machine. This didn't really happen on the previous version.

**Comment by MehediH** [comment]
Should be fixed in 5.1
