### ISSUE TITLE
[Windows] [Nit] Missing icon and version info 

### ISSUE THREAD

**Issue by Stanzilla** [MehediH/Tweeten#19]
The programs and features list entry for Tweeten on Windows is missing an icon and version/website info and you might wanna put the name without the version affixed
![explorer_2016-03-11_23-56-03](https://cloud.githubusercontent.com/assets/75278/14408327/5743c622-fef0-11e5-95dc-13f5cbcf04f0.png)

**Comment by MehediH** [comment]
Fixed with Tweeten 1.9 - tweeten.xyz/windows
