### ISSUE TITLE
Warning Message: TweetDeck no longer has permission to access your main account.

### ISSUE THREAD

**Issue by fear025** [MehediH/Tweeten#190]
This is in version 5.0.5.

I am receiving the following big blue message on the bottom of my screen:
"TWEETDECK NO LONGER HAS PERMISSION TO ACCESS YOUR MAIN LOGIN ACCOUNT [@MYACCOUNT]. YOU WILL BE LOGGED OUT TO PREVENT UNAUTHORIZED ACCESS".

I have tried exiting Tweeten and launching it again, logging off and logging back on, and hitting the "Reset Tweeten and Start Fresh" button, but the message keeps appearing and disappearing. The application appears to keep working and loading new tweets, but because I keep the Tweeten window on the left hand side of my screen, the warning message takes up a good quarter of the entire Tweeten window.

**Comment by MehediH** [comment]
Not a Tweeten issue.
