### ISSUE TITLE
[v5.1.0 | Windows (64-bit)] New Emoji picker displays emoji in compose box, but doesn't post them

### ISSUE THREAD

**Issue by BradyThe** [MehediH/Tweeten#193]
![710_anUWOZOf4SnYRp7OSGjs](https://user-images.githubusercontent.com/8181555/90179699-23080e80-ddae-11ea-8edc-ee6d9fa079c5.png)  
![711_5aSCK0XX9x83gL5q0jL1](https://user-images.githubusercontent.com/8181555/90179705-269b9580-ddae-11ea-8b34-22be0f5b1969.png)  
![712_wl0lQtorrEsytS37t4rk](https://user-images.githubusercontent.com/8181555/90179707-269b9580-ddae-11ea-942a-0d60e2aa062b.png)

Cheers

**Comment by haverholm** [comment]
Same here. 

As a workaround I've found that cutting the emoji from the compose field and pasting them back in registers them in the posted tweet. It's a somewhat frustrating solution to the emoji picker simply not working, though.

**Comment by haverholm** [comment]
Also, @MehediH -- it's not encouraging that @BradyThe 's flagging **a prominent, touted feature not doing what it says on the tin** goes unaddressed for almost a month.

**Comment by MehediH** [comment]
> Also, @MehediH -- it's not encouraging that @BradyThe 's flagging **a prominent, touted feature not doing what it says on the tin** goes unaddressed for almost a month.

I have already confirmed this bug and it will be eventually fixed when I have the time to work on Tweeten. The app is a side project for me and I have a full time job and other personal things to take care of. So if you have any problems with me not fixing bugs quickly enough for you, you can stop using the app and find an alternative 👍🏽

**Comment by MehediH** [comment]
Fixed in 5.2.0. Thanks!
