### ISSUE TITLE
Client-wide Columns not updating

### ISSUE THREAD

**Issue by jaydeflix** [MehediH/Tweeten#198]
The Mentions/Direct Messages columns are both not populating anymore after 5.1.0 (I think).

**Comment by jaydeflix** [comment]
I should add: 
Problem also exists on Scheduled (all accounts)

All other column types seem fine.

**Comment by jaydeflix** [comment]
FWIW, these columns are still not updating for me.

**Comment by MehediH** [comment]
Interesting, have you checked if this issue occurs on tweetdeck.twitter.com?

**Comment by jaydeflix** [comment]
I honestly had thought that was a Tweeten feature over Tweetdeck! Yeah, tweetdeck is throwing a loading circle too. Closing this out (but any tips would be appreciated, if you have them... I'm assuming the entire functionality isn't broken..)
