### ISSUE TITLE
Virus in new tweeten 

### ISSUE THREAD

**Issue by manderley3** [MehediH/Tweeten#20]
the virus has been removed but now tweeten does not work
Scan Results
The Virus Shield detected one infected item.
Scan Results
File Name	Infection	Action
C:\Users\user\AppData\Local\Tweeten\tweeten.exe	Gen:Variant.Razy.191688	Moved to Quarantine

**Comment by manderley3** [comment]
Deleted it, tried downloading a few times but always had virus. Deleted again and found 4 0 2 on the internet to download that.  That did not have a virus and back working again.

**Comment by MehediH** [comment]
There is no "virus" in Tweeten. The app isn't signed which makes anti-viruses think it's not safe.
