### ISSUE TITLE
Recurring AutoUpdate Error

### ISSUE THREAD

**Issue by korgano** [MehediH/Tweeten#202]
I've been getting this error for the last few days. Not sure exactly what caused this, but I think it might have happened while I was adjusting some firewall settings. I could probably get rid of this with a reboot, but I don't like rebooting my PC unless necessary.

`[Window Title] Error [Main Instruction] A JavaScript error occurred in the main process [Content] Uncaught Exception: Error: Object has been destroyed at autoUpdate (C:\Users\User\AppData\Local\Programs\Tweeten\resources\app.asar\main.js:747:16) at Timeout._onTimeout (C:\Users\User\AppData\Local\Programs\Tweeten\resources\app.asar\main.js:178:9) at listOnTimeout (internal/timers.js:531:17) at processTimers (internal/timers.js:475:7) [OK]`

Still happens with the app open and even after it successfully does an auto-update check.

**Comment by MehediH** [comment]
Do you still have this issue?
