### ISSUE TITLE
Suggestion: Use of multiple accounts similar to Twitter.com

### ISSUE THREAD

**Issue by Mythotical** [MehediH/Tweeten#203]
I'm not sure if this would be possible to add to your Tweeten app, which I love by the way, but I like how Twitter.com allows me to add all my accounts and switch between them. Is that a possible feature coming in Tweeten at a later time or could be a feature to be added?

**Comment by Mythotical** [comment]
I saw the way I add more accounts but what I'm mainly wondering about is the ability to click my profile picture and choose another account.

**Comment by MehediH** [comment]
Sorry, this is not possible at the moment and not something that can be added from Tweeten's side as it relies heavily on TweetDeck.
