### ISSUE TITLE
Pasting images goes to wrong compose window

### ISSUE THREAD

**Issue by jaydeflix** [MehediH/Tweeten#207]
Steps to repro
Have a generic tweets column and a DM column.
Hit reply on any tweet in the tweets column.
Open a DM from the DMs column.
Paste a graphic into the compose window.

At this point tweeten should move the compose window to the left docked compose bar but will have pasted the graphic to to the tweet reply rather than the DM reply.

As this can cause "private" information to be shared publicly, I would mark this as a high severity issue and potential security concern.

**Comment by MehediH** [comment]
Fixed in 5.2.0. Thanks!
