### ISSUE TITLE
(feature request) Right Click - Open image in browser

### ISSUE THREAD

**Issue by Dundes** [MehediH/Tweeten#209]
Keeping Tweeten window narrow on screen, clicking on an image to see it magnified it still small due to the limited with of the application; it would be great to have the possibility to right-click the tweet image (and video too, if possible) and have command to open it directly into browser, just to see it in wider window. Now it is possible, but opening in browser before the twitter website. Thank you
![IMG_20201217_113022](https://user-images.githubusercontent.com/61359194/102476388-53f99800-405b-11eb-867b-8006b4cb8e95.png)

**Comment by MehediH** [comment]
Added in 5.2.0. Thanks!
