### ISSUE TITLE
Popups are enabled but don't 'popup'?

### ISSUE THREAD

**Issue by kimakoh** [MehediH/Tweeten#21]
I have the windows app on my desktop and enabled popups for my notifications, however whenever I do get a new notif, a popup doesn't show up. So then i have to resort to the notif sound to play in order to know if i got a new notification. How do I fix this?

**Comment by kimakoh** [comment]
bump again

**Comment by MehediH** [comment]
This is only supported in Windows 10 as the framework we are using doesn't support desktop notifications yet. If you want to enable it in Windows 10, go to tweetdeck.com, enable desktop notifications there and you'll get asked for permission. So grant the permission, and then you'll get notifications in Windows 10. Sorry, can't do anything for support in older Windows.
