### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by dotamir** [MehediH/Tweeten#21]
Hey, Thank you for making this app.
Do you have a plan for Linux version? I'm very curious about that. If you want help, you can count on me :)

**Comment by MehediH** [comment]
Not at the moment

**Comment by iamecc** [comment]
> Hey, Thank you for making this app.
> Do you have a plan for Linux version? I'm very curious about that. If you want help, you can count on me :)

I found that it works nicely under WINE, with full window, all notifications, tray icon and everything. You could give it a try.

**Comment by michaelfresco** [comment]
@iamecc can you still install the recent Tween versions with Wine? I tried it with ubuntu 18.04 and wine 4.0.3 but the installation process failed.
