### ISSUE TITLE
Tweeten don't open GUIs

### ISSUE THREAD

**Issue by mitim** [MehediH/Tweeten#210]
To updated 5.2.
The update is successful (no messages).
But don't display GUIs in ver.5.2.
Windows task manager said 3 background processes of tweeten in that time.
I tried uninstall and install, restart windows ... but occurred same result.

**Comment by MehediH** [comment]
Hi can you check if the app is running on the tray?

Otherwise, try completely uninstalling the app, deleting the Tweeten folder in %appdata% and reinstalling it.

**Comment by mitim** [comment]
No, app is not on tray.
I'm going to try completely uninstalling.

**Comment by mitim** [comment]
Hi,
I tried completely uninstalling (and double-checked nothing files/folders "tweeten" on PC using search everything),
and re-start windows, re-installed tweeten.
But the result did not change.

I'm using Windows 10 Home Japanese (ver.1909).
Memory is 32GB installed.
Any Japanese users said "not working new version".
Please check the app program.
thanks.

**Comment by TamaZooo** [comment]
hi.
i have same issues too.

the GUI did not start even with the specified recovery plan.
(uninstall, confirm data erasure of% appdata%, reinstall)

the process(Tweeten.exe) could not be terminated from Task Manager.
i used cmd to force it to terminate with the `Taskkill` command.

what i was interested in was that in "5.2.0.", Only 3 Tweeten.exe processes were started, but in "5.1.0.", 6 Tweeten.exe processes were started.

the following log appeared in the log file. 
(%appdata&\Tweeten\logs\main.log)
`[2020-12-20 02:06:28.224] [info] Is dev? false`

my environment is Microsoft Windows 10 Pro 10.0.19042 (20H2).
thanks.

**Comment by kui** [comment]
Same issue.

I executed tweeten 5.2.0 in Power Shell:

```
PS C:\Users\kui> C:\Users\kui\AppData\Local\Programs\Tweeten\Tweeten.exe
PS C:\Users\kui>
03:20:12.103 > Is dev? false
(node:2528) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:2528) UnhandledPromiseRejectionWarning: Error: Invalid language code provided: "ja" is not a valid language code
    at createWindow (C:\Users\kui\AppData\Local\Programs\Tweeten\resources\app.asar\main.js:79:34)
    at C:\Users\kui\AppData\Local\Programs\Tweeten\resources\app.asar\main.js:532:3
(node:2528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It looks a problem in "ja" language windows.

My windows use with japanese too:

* Windows 10 Pro
* Version: 2004
* OS build 19041.572

**Comment by MehediH** [comment]
@kui thanks, that's very helpful -- I will be releasing a new patch shortly.

**Comment by MehediH** [comment]
This should be fixed now in 5.2.1, please let me know if you still experience the problem.

**Comment by kui** [comment]
It seems to work fine for my environment. Thanks!

**Comment by mitim** [comment]
Yeah!
5.2.1 is working in my PC perfectly!

Thanks for your work, MehediH.
