### ISSUE TITLE
Starting Tweeten from command prompt

### ISSUE THREAD

**Issue by sabs212** [MehediH/Tweeten#214]
Hi, love the app, thanks! I donated via PayPal.

I have a question for you.
I use a .bat file to launch several apps via command prompt.
When Tweeten is started via command prompt, sometimes the text below is displayed. This process seems to hang. The command prompt window cannot be closed or Tweeten exits.

Is there an argument I can use or other command/setting to start Tweeten which bypasses this update check so the command prompt window can be closed? Thank you!

Command used:     start C:\Users\admin\AppData\Local\Programs\Tweeten\Tweeten.exe

10:59:46.914 > Is dev? false
(node:18624) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:18624) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
11:00:05.437 > Checking for updates (isPatch:false)
Checking for update
Update for version 5.2.1 is not available (latest version: 5.2.1, downgrade is disallowed).
11:00:11.331 > Update not available

**Comment by MehediH** [comment]
Thanks for the donation! I am looking into this and will respond if I have any updates.

**Comment by MehediH** [comment]
@sabs212 Try `explorer C:\Users\admin\AppData\Local\Programs\Tweeten\Tweeten.exe`

**Comment by sabs212** [comment]
Works perfectly - thank you!
