### ISSUE TITLE
Tweets & Retweets

### ISSUE THREAD

**Issue by JackBeckitt** [MehediH/Tweeten#215]
Hello there

My tweets & RTs are not appearing in my User column - only works when I use Twitter itself - any ideas?

Kind regards

**Comment by BradyThe** [comment]
Have you edited the column options (three dots -> Tweet content, Tweet authors)?

**Comment by JackBeckitt** [comment]
Hi

No, I did to try get them back with no success, all back to default. I can tweet/retweet on Twitter and they appear in my user column on Tweetdeck, but nothing shows when I use tweetdeck

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
