### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by BradyThe** [MehediH/Tweeten#216]
Unfortunately I activated 'Always on top' with a shortcut I wasn't aware of.

Problems:
- I didn't read the notification, thus I don't know the shortcut
- 'Settings -> Keyboard shortcuts' doesn't list the shortcut
- 'Settings' doesn't offer an 'Always on top' option
- Tweetenapp doesn't seem to read imported backups ("aot":false)

Help would be appreciated. Thanks!

_Edit: Resetting the settings and importing the backup did decide to work.
Still, an updated 'Keyboard shortcuts' list and/or adding an option in the settings would probably be a good idea, if this version of Tweeten is still being maintained._

**Comment by MehediH** [comment]
This is fixed in newer versions of Tweeten :)
