### ISSUE TITLE
[FEATURE] Option to have a "clear all" button on main window

### ISSUE THREAD

**Issue by bambooLoutre** [MehediH/Tweeten#217]
Hello,

I use tweeten regularly, and one action i do all day long is to "clear columns" in order to see "only new tweets" since previous time.

So for each column, i click "..." -> Clear -> "..."

I would love to have the ability to have a button on bottom left column with the ability to clear all columns at once.

**Comment by MehediH** [comment]
This is already an option in the settings.

**Comment by Taizunz** [comment]
Where exactly is this option?
There's an option to enable a quick action for clearing a single column, but I see no options for enabling a button to clear all columns at once.

**Comment by MehediH** [comment]
@Taizunz there's no option to clear *all* columns at once, this has not been requested in the past. I will add an option for it.
