### ISSUE TITLE
Not really a bug... more of a request if possible

### ISSUE THREAD

**Issue by hobybrenner** [MehediH/Tweeten#223]
I have been a fan of the large widescreen timeline view I get with Tweetium, but dev has stagnated, and I haven't seen anyone replicate the view that wraps the timeline across the entire page.  Its handy to be able to see so much information on a large screen.  Any chance this could be some sort of option to enable "Home" or TimeLine to wrap all columns?

**Comment by MehediH** [comment]
I have had this request before and honestly, it would be foolish to add the feature atm. TweetDeck is about to get a major overhaul so it's best to wait for that to happen before working on major things like this :)
