### ISSUE TITLE
clear quick action for search columns

### ISSUE THREAD

**Issue by ismellpillows** [MehediH/Tweeten#227]
I use a filtered search column as one of my feeds. However, the clear column button doesn't show up on it like it does for other ones.

A toggle for this clear button or a hotkey to clear a column would help, to avoid having to click thrice.

Search vs other column, clear button doesn't show up:
![as](https://user-images.githubusercontent.com/54971111/113943386-756fc280-97b7-11eb-9a7e-156f61b2a113.png)

**Comment by MehediH** [comment]
Fixed in 5.5.0
