### ISSUE TITLE
5.3.0 prevents M1 Mac Mini turn off display

### ISSUE THREAD

**Issue by tapetum** [MehediH/Tweeten#228]
On Mac Mini M1 with Big Sur 11.2.3, Tweeten 5.3.0 prevents the Energy Saver from turning off the display when prevent computer from sleeping is checked. If the prevent computer from sleeping is unchecked, the computer does sleep. Prior versions allowed the display to be turned off without sleeping the computer. 
![image](https://user-images.githubusercontent.com/11934138/113947337-ad7f0180-97c7-11eb-8854-68043b1140a8.png)

**Comment by MehediH** [comment]
Duplicate of #231

**Comment by tapetum** [comment]
Same issue for me with 5.4.0.
