### ISSUE TITLE
Problem playing videos after updating to 5.3

### ISSUE THREAD

**Issue by EvanBae** [MehediH/Tweeten#230]
I have had issues with opening videos in Tweeten lately and seemingly since updating to ver 5. 3 When I open Tweeten I can play videos but after a while I cant. The video box will open and either show a blank box with the play bar at the bottom, or sometimes it will show the opening scene of still frame of the start of the video.  Some wil play yet others wont.  But when I shut down Tweeten and restart it, the same video that wouldnt play, now will play.  And later again, not long, the same thing happens.  Have to constantly close Tweeten and restart in order to watch a video I want to see.

**Comment by RealSkeptic** [comment]
Same here. MacOS ver. 5.3.0.

Some videos play.

Some only play for a second and close.

Some don't even display a frame.

**Comment by MehediH** [comment]
Hi, are you still having this issue? I can't seem to be able to reproduce this on my end.

**Comment by MehediH** [comment]
Fixed in 5.5.0

**Comment by RealSkeptic** [comment]
I had a video today that stopped at around 3 seconds. So I'm not sure it's fully fixed.
