### ISSUE TITLE
Replies, RT and likes numbers are not updating in the Home Tab

### ISSUE THREAD

**Issue by thanrek** [MehediH/Tweeten#234]
Once a tweet appears in the Home Tab, the number of replies, RTs and likes will stay the same as what they were when the tweet was loaded. 

Clicking on the tweet will show correct numbers but the Home Tab won't.

**Comment by MehediH** [comment]
This is a TweetDeck issue, which is what Tweeten is built on top of. Please direct this request/bug to the TweetDeck/Twitter deam.

**Comment by thanrek** [comment]
thank you, I wasn't aware
