### ISSUE TITLE
Tweeten prevents power management to turn off the monitor

### ISSUE THREAD

**Issue by withinpipo** [MehediH/Tweeten#235]
C:\Windows\system32>powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume4\Users\withinpipo\AppData\Local\Programs\Tweeten\Tweeten.exe
Video Wake Lock

Closing the app then relaunching it give me the lock right away

**Comment by jetuser** [comment]
I'm seeing the same thing myself. I can't seem to narrow down a specific behavior that causes this, seemingly random.

**Comment by MehediH** [comment]
Duplicate of #231
