### ISSUE TITLE
Problem closing and reopening the app on macOS

### ISSUE THREAD

**Issue by LucasN0611** [MehediH/Tweeten#238]
After closing the app on macOS Big Sur, I can’t reopen it by just clicking the icon like normal. I have to completely quit the app and then reopen it for it to show up.

**Comment by MehediH** [comment]
Are you on an M1 machine?

**Comment by LucasN0611** [comment]
No, I’m on a 2017 MacBook Pro with an Intel Core i5

**Comment by h0jeZvgoxFepBQ2C** [comment]
Same here, its broken since the last 2-3 versions. Also I installed now the latest version, and I cant open it anymore at all. It just freezes and i see no GUI. I can only force close it now again.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I also tried to downgrade to 5.3 again, but also doesn't work anymore. I doubleclick the Application, nothing shows and I can only force close it.

**Comment by MehediH** [comment]
This will be fixed in the next version.

**Comment by h0jeZvgoxFepBQ2C** [comment]
If it helps, I can see following highlighted entries in the console.app:

![Bildschirmfoto 2021-07-16 um 11 02 14](https://user-images.githubusercontent.com/10075/125922462-0dfaa0e9-cc08-4265-8cc1-04ac4ec1c78c.png)

Is there any ETA when the new version gets released? I cant use Tweeten at all right now.
Thank you ❤️

**Comment by MehediH** [comment]
Next week :) 

You should still be able to use Tweeten if you just quit the app (CMD+Q), and reopen it.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Nope, unfortunately its not starting at all anymore. I can start it, but no GUI shows up. I can only close it then again. So no GUI anymore :/

**Comment by MehediH** [comment]
I will look into this.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I just restartet, but didn't change anything. It still shows no GUI and I can only close it. Guess I will wait for the next release.. Thanks! ❤️
