### ISSUE TITLE
Auto update version check every half an hour

### ISSUE THREAD

**Issue by jututt** [MehediH/Tweeten#240]
Looking into `%appdata%\Roaming\Tweeten\logs\main.log` I can see that that Tweeten checks for updates every half an hour, even if I deselected
`Enable auto app updates`
`Enable automatic hot fixes`
How can I prevent Tweeten checking that?
You should reduce the frequency of that check every 6 hours or so, imo.

**Comment by MehediH** [comment]
Fixed in 5.4.0
