### ISSUE TITLE
Link shortener options stopped working?

### ISSUE THREAD

**Issue by Neobond** [MehediH/Tweeten#242]
I went to use it today and see that bit.ly no longer supports the API method, it is switched to OAUTH access token but in Tweeten it is still Bit.ly username / Bit.ly API Key method, which doesn't work.

For the purposes of making a tweet I selected TWITTER shortening and saw that the shortening did not actually apply to the tweet I sent. So it looks like both methods stopped working. I also seem to remember being able to select which accounts the shortening applied to, and that is also missing from the settings.

**Comment by MehediH** [comment]
TweetDeck has not updated its integration for Bit.ly, so there is nothing I can do about it. Tweeten simply uses the TweetDeck link shortening feature.
