### ISSUE TITLE
The size when playing a GIF video is too large

### ISSUE THREAD

**Issue by kreis117** [MehediH/Tweeten#243]
The size when playing a GIF video is large, and I cannot close the GIF video by operating the mouse.
Since there is no margin on the screen, the video cannot be closed by operating the mouse.
I want Gif videos to play in the same size as regular videos.

![参考画像](https://user-images.githubusercontent.com/74777259/121804825-39f3e780-cc83-11eb-8864-0b3a3068ab38.png)

**Comment by MehediH** [comment]
Fixed in 5.5.0
