### ISSUE TITLE
Minor UX improvement on DM groups - reacts

### ISSUE THREAD

**Issue by AlexLaSarthe** [MehediH/Tweeten#244]
I use 5.3.0 for a couple of group DMs with 30-50 people in them. Whenever someone posts something funny it will get 5-10 reacts. In 5.3.0 a Reaction is displayed as something that looks like a tweet which says "@name reacted to your tweet with \<emoji>"

So what I end up with on the screen (even a 1080p screen) in that DM group is the original DM and then a screenful of reacts...

Could it be possible to either shorten the message (possibly even to "@mention reacted \<emoji>") or do it like the Twitter website does (and Slack and Discord and Rocketchat do...)

**Comment by MehediH** [comment]
This is not something I can fix on my end, please ask TweetDeck.
