### ISSUE TITLE
Search Location Breaks

### ISSUE THREAD

**Issue by MrHuggy** [MehediH/Tweeten#247]
Running on Windows 10

When you do a search on a word or tag and you filter by location if the location does not come up on the list then the location function stops working at all. Closing and restating the client doesn't work to fix it, you have to reboot the computer for it to work again.

**Comment by MehediH** [comment]
What version are you running? The issue doesn't reproduce for me

**Comment by MrHuggy** [comment]
Sorry about taking ages to get back to you, been busy.

Tweeten 5.4.0, Windows 10 21H1 19043.1083

Type in a search for something
Type in a location i.e Seattle [The location should come up if a major city etc]

Ok working fine there, now

Type in something to search
Type in a location and miss spell it or a location that doesn't come up i.e Saettle [Now the location will not be recognised]
Type in the right  location. i.e Seattle [The right location will not be recognised].

Close the app and reopen

Type in something to search
Type in a location i.e Seattle [Now the location will not be recognised]

I tried the same thing in Tweetdeck and guess what Tweetdeck brakes as well. So it looks like a bug on Twitters end.

**Comment by MehediH** [comment]
Yeah, I am afraid this is beyond the scope of Tweeten.
