### ISSUE TITLE
Add to List window crashes on scroll

### ISSUE THREAD

**Issue by jaydeflix** [MehediH/Tweeten#249]
Windows 11 (Version 21H2 OS Builder 22000.71)
Tweeten 5.4.0

Repro:
Have ~15+ lists (enough that you need to scroll)
Pull up the left profile tab (click on a user, search for a user)
Click the three dot action menu
Click Add or Remove from list
Attempt to scroll the window (I tried using the scroll bar and the scroll wheel)
At this point, the window should disappear

I didn't see an existing issue on a search for List so making a new one.

Editing to add: Works fine in Tweetdeck

**Comment by MehediH** [comment]
Fixed in 5.5.0
