### ISSUE TITLE
Feature request: Pause timeline position

### ISSUE THREAD

**Issue by davshoward** [MehediH/Tweeten#25]
It would be great if you could pause the position of a column timeline. Similar to how scrolling down loads the most recent tweets above that threshold, but a) without needing to scroll and b) without grouping them into "Load 25 more".

**Comment by MehediH** [comment]
Can you go into a bit of detail about this?

**Comment by davshoward** [comment]
Sure. In many of the mobile Twitter apps I use when you open the app, it keeps your last read tweet at the top and then loads the new Tweets above that Tweet. Often I'll have Tweeten open for prolonged periods but all the new tweets automatically get pushed to the top and then hide other Tweets under "load more". It can make it difficult to know what's new.

My preference (maybe as an option) would be for your scroll position to be paused, whilst new Tweets are loaded above that you can then scroll up to read.

Let me know if that makes sense or not :-)

**Comment by MehediH** [comment]
Due to how TweetDeck loads tweets in timeline this unfortunately isn't possible to implement.

**Comment by MehediH** [comment]
Due to how TweetDeck loads tweets in timeline this unfortunately isn't possible to implement.
