### ISSUE TITLE
[Feature Request] "Close To Tray"

### ISSUE THREAD

**Issue by pingufetch5** [MehediH/Tweeten#25]
I would like to request a "close to tray option" so that lets the program minimize itself to your system tray when pressing the close button rather then closing.

**Comment by MehediH** [comment]
This will be added with a update soon,

**Comment by EmuAGR** [comment]
I'm also looking forward to this. I always close Tweeten by mistake, and "Minimize to tray" option doesn't remember its position between the tray icons, goes straight to the hidden icons panel.

**Comment by MehediH** [comment]
Added with 1.9 - tweeten.xyz
