### ISSUE TITLE
Feature Request: Mute new, but copied tweets

### ISSUE THREAD

**Issue by NerdCowboy** [MehediH/Tweeten#26]
This has been a long standing annoyance from a lot of accounts I follow. They'll tweet new, identical tweets from the past on a regular basis that I've seen a dozen times. I understand they want to surface old content for new followers, but as a long time follower, I'm tired of seeing the same thing over and over again.

I was thinking it'd be awesome if we could add a feature where you can mute any future, identical tweets from a user just as you can mute keywords or accounts.

**Comment by MehediH** [comment]
Yeah, impossible to implement on the client side.
