### ISSUE TITLE
Twitter Mute Lists not always coming through

### ISSUE THREAD

**Issue by NerdCowboy** [MehediH/Tweeten#28]
I have a lot of things on Twitter's official mute list (not Tweeten) as I don't want to see any political  stuff or the latest controversy Twitter is mad at.

This could be a bug with the feed Twitter is sending over to Tweeten, but I'm still getting some things that are on my Twitter mute list that are still coming through.

I would just use the Tweeten mute list, but since there's not a mobile client, I use Tweetbot, so handling the mute list in one location is preferable.

**Comment by MehediH** [comment]
Tweeten isn't supposed to sync your filters from Twitter.
