### ISSUE TITLE
RT/Fav icons are awful

### ISSUE THREAD

**Issue by throwaway666** [MehediH/Tweeten#28]
i was completely in love with tweeten until this. my feed is an incomprehensible mess of darkened avatars completely obscured by RT icons, instead of being like tweetdeck where avatars are visible and i can recognize people immediately. would switch to tweeten permanently if not for this, but til then back to web tweetdeck.

**Comment by MehediH** [comment]
You can now get the classic TweetDeck icons with Tweeten 1.9 - tweeten.xyz
