### ISSUE TITLE
Every word is underlined by spell checker (and disable it)

### ISSUE THREAD

**Issue by EmuAGR** [MehediH/Tweeten#29]
Every tweet I'm writing has every word underlined red. It doesn't matter if I'm writing in Spanish or English. Also, I don't want this feature at all, I can spell properly without the help of a dictionary (and a dictionary won't help with syntax hesitation).

**Comment by MehediH** [comment]
Spell check is only available for English and you can disable it on Tweeten 1.9 - https://t.co/4MkxuLhDou
