### ISSUE TITLE
Tweeten won't reload after error loading TweetDeck preview

### ISSUE THREAD

**Issue by BVig** [MehediH/Tweeten#301]
Hi - 

I just installed Tweeten for macOS today, and ran into an issue when first setting it up. It asked me about using the new TweetDeck preview, which I clicked "yes" to. Now I'm stuck in a loop with this error message: 

"Tweeten has detected you are using the new TweetDeck Preview. Unfortunately, Tweeten does not yet support the new TweetDeck. Tweeten will now reload to load the classic TweetDeck."

Unfortunately, when I click OK to reload it, the error message simply returns. I've uninstalled/reinstalled several times, and I can't find any folders in the cache or library assocated with the app that contain config files that might need deleting to fix the problem. 

Help!

**Comment by TheMurg** [comment]
same issue.   I found that if you close tweeten, then delete ~/Library/Application Support/Tweeten/config.json.  it will start over with the setup and you can login.

**Comment by dbrisinda** [comment]
Same issue here as of October 23, 2022 on macOS 12.5.1

**Comment by theapathyimp** [comment]
This is also happening on Windows as of version 5.5.0. I solved it by completely deleting the "Tweeten" folder and all of its contents in my Roaming AppData: C:\Users\[YourUsername]\AppData\Roaming\Tweeten.

Doing so let me log in again, and I was able to get to the dashboard.

**Comment by dbrisinda** [comment]
> same issue. I found that if you close tweeten, then delete ~/Library/Application Support/Tweeten/config.json. it will start over with the setup and you can login.

Didn't work.

**Comment by dbrisinda** [comment]
Experienced this problem after upgrading to macOS Monterey 12.6.3. Can't get it to load.

**Comment by daydayup763** [comment]
I had the same problem and the answers given above did not solve the problem.

**Comment by Oral-B** [comment]
Same issue here, on a brand new Win11 install. Tried @theapathyimp 's solution, didn't work.

**Comment by Impair1980** [comment]
Does anyone know what the solution is?
![20230225_160857](https://user-images.githubusercontent.com/110308354/221364528-fb41d1d2-f243-4e77-b73d-e9473a8d2a9d.jpg)

**Comment by Oral-B** [comment]
I wish I did. I tried everthing, uninstalling, re-installing, using the MS Store app, the stand-alone installer, the exe from the github page, tinkering with the json and other files as suggested above, to no avail. Still stuck on the error message loop.

The strange thing is that this is on a brand new Win11 install, on the exact same machine that I used Tweeten with no issues before, also on a fresh Win11 install from a few months ago.

**Comment by telstarone** [comment]
Same issue here.

**Comment by around84** [comment]
Yes, I have the same problem.

<img width="1720" alt="Снимок экрана 2023-03-11 в 01 10 39" src="https://user-images.githubusercontent.com/18323349/224437873-0718812c-f1e3-4f50-b2ec-a1e46b73fb07.png">

**Comment by d3f4ultt** [comment]
ive literally tried everything from Uninstalling, clearing AppData, restarting desktop but still getting the error about TweetDeck like others on v5.5.0

**Comment by ovitrif** [comment]
> ~/Library/Application Support/Tweeten/config.json

You couldn't say to run in terminal this command, now could you? 🤦🏻‍♂️

```sh
rm ~/Library/Application\ Support/Tweeten/config.json
```

**Comment by ovitrif** [comment]
Anyways this is a BS and dead project. Even if you cleanup the `config.json`, it will just hang on the next screen. Uninstall it and use TweetDeck desktop with Unite or something.

<img width="1268" alt="Screenshot 2023-04-28 at 10 20 32" src="https://user-images.githubusercontent.com/4588074/235094699-8ecdb4fb-d44b-4b70-af22-5de6c749c29b.png">

**Comment by MehediH** [comment]
For someone who works at a company like Automattic, @ovitrif you sure do lack the ability to read, common sense, and empathy. Here's the announcement of this project being discontinued: https://github.com/MehediH/Tweeten/discussions/327

Before you come online and be a dick to people on this thread, learn to read and take your entitled ass somewhere else.

**Comment by MehediH** [comment]
For everyone else on this thread, Tweeten has been discontinued, I apologise for the inconvenience.

**Comment by ovitrif** [comment]
@MehediH Sorry mate, but you should follow up on users of your own open source project. This felt unacceptable for me. Thank you for handling this properly, I apologize for being an ass 🙏
