### ISSUE TITLE
Twitter apparently has banned third-party apps

### ISSUE THREAD

**Issue by stevegoldfield** [MehediH/Tweeten#323]
I read today that Twitter has banned third-party apps and no longer provides an API. However, Tweeten is still working so far; perhaps Twitter doesn't know about it? Do you have any further word on whether Tweeten is going to lose its link to Twitter?

Here's a link to the story. https://www.macrumors.com/2023/01/19/twitter-bans-third-party-apps/

**Comment by JayBrown** [comment]
Shouldn't be a problem. Afaict Tweeten is only accessing tweetdeck.twitter.com, so it's not a standalone client using the Twitter API, but more like a browser for that specific Twitter page.

**Comment by JimDop** [comment]
wow, no 3rd party ?  how suck is that

**Comment by JayBrown** [comment]
New development is that TweetDeck will apparently only be available to Twitter Blue users. So Tweeten might stop working for some of us, unless we pay up.

**Comment by cordial** [comment]
It's stopped working, presumably due to the none free API now?

**Comment by stevegoldfield** [comment]
It's still working for me, and I don't have Twitter Blue.

**Comment by JayBrown** [comment]
Stopped working for me tonight… noticed that likes didn't go through. Tried to reload TweetDeck, but then got logged out. Logging back in worked, but then Tweeten displayed the error prompt that it had to revert from the preview version of TweetDeck to the default version, and that's where it got stuck. Plus: JavaScript error after Tweeten quit.

**Comment by MehediH** [comment]
https://github.com/MehediH/Tweeten/discussions/327
