### ISSUE TITLE
Stuck on ->Tweeten has detected you are using the new TweetDeck Preview

### ISSUE THREAD

**Issue by malshar** [MehediH/Tweeten#324]
I got a notification to use the Tweetdeck preview and I wish I didn't, now Tweeten is stuck on a notification that I am still using the preview even though I switched to classic mode. any help?
![Screenshot 2023-01-31 at 6 55 24 AM](https://user-images.githubusercontent.com/1936555/215659151-eb3bfbc5-a88d-44d1-9a7f-fcd98aab873a.png)

**Comment by ElBearsidente** [comment]
Same issue, and none of the solutions mentioned here worked for me.

**Comment by oogami-kero** [comment]
Seems to be an issue with the new Tweetdeck preview version. I think a possible workaround would be to set the tweetdeck_version parameters in document.cookie to "legacy".

**Comment by ZipsHub** [comment]
Setting document.cookie to legacy did not seem to work for me.

Here's what I tried to use, so maybe this was incorrect: 
document.cookie = "tweetdeck_version=legacy"

**Comment by cujojp** [comment]
Just confirmed, Tweetdeck will redirect the user back to `twitter.com` and then the user will be stuck if the cookie `tweetdeck_version` is set to `legacy`.

It appears Twitter is EOL'ing Tweetdeck.com with the `legacy` view. So I don't know or think it would be possible to set it back to `legacy` and use Tweeten, until twitter fixes or removes that redirect.

![tweetdeck](https://user-images.githubusercontent.com/870893/217685421-b3fa4501-5d06-4fa4-abaf-d5252ce19cf6.gif)

**Comment by ElBearsidente** [comment]
I'm seeing the exact same thing.

**Comment by ferrazpedro** [comment]
I think it's now working again with the legacy cookie, at least in my machine. How do I use it in Tweeten?

**Comment by MehediH** [comment]
https://github.com/MehediH/Tweeten/discussions/327
