### ISSUE TITLE
[Bug] large amount of lag when expanding a tweet

### ISSUE THREAD

**Issue by RheingoldRiver** [MehediH/Tweeten#33]
Especially when there's a link/media attachment, the client will often lag out for 5-15 seconds or so when I expand a tweet. OS is Windows 7 and I have the most recent version as of today, April 22nd.

**Comment by MehediH** [comment]
This is caused by the Twitter Cards support. We will add the ability to disable this in a few months

**Comment by RheingoldRiver** [comment]
Any chance of having that option sooner? It makes the app pretty difficult to use.

**Comment by MehediH** [comment]
Added with Tweeten 1.9, just untick the "Enable Twitter Card integration" from Settings: https://t.co/4MkxuLhDou

**Comment by jonkyr** [comment]
I think this bug is still present after 1.9. It's also lagging when i move a column (from left to right or vice versa). Got to check these two again though. But maybe someone can confirm it for me as well.

**Comment by MehediH** [comment]
@jonkyr Disable the "Twitter Card integration" from Settings.
