### ISSUE TITLE
Muted account isn't muted in Activity feed

### ISSUE THREAD

**Issue by Gyoo** [MehediH/Tweeten#33]
See attached file. I have the account in the quote muted on Twitter. It is muted correctly on my Home feed, but not on the Activity feed.
![tweeten_2017-10-08_17-15-28](https://user-images.githubusercontent.com/3592205/31318078-7d760804-ac4c-11e7-818f-f780f978f571.png)

**Comment by MehediH** [comment]
This is more of an issue on TweetDeck's end. Tweeten is based on TweetDeck, we can't do anything about this.
