### ISSUE TITLE
No notifications since fall creators update

### ISSUE THREAD

**Issue by iekozz** [MehediH/Tweeten#34]
Hi there, 

I did a upgrade from a earlier build to the new  fall creators update. (build 16299.19). The notifications stopped working entirely. This is what I am seeing:

1: Notifications are enabled on the app. 
2: Tweeten does not show up in the notification settings (Settings -> Apps -> Notifications)

I tried the following things already:

1: Repair tweeten via windows settings
2: Delete data via windows settings 
3: Unistalled and reinstalled both the uwp and standard windows app
4: Performed a fresh install of the Windows 10 OS. (The latest build as mentioned above). 

I am not seeing what I am doing wrong here. Are there any more suggestions I can try or is this just a bug on my machine? It worked perfect before. 

Thanks

**Comment by iekozz** [comment]
Forgot to mention, running tweeten 4.1.0 on Windows 10 64-bit.

**Comment by d4k0** [comment]
Same problem here with Tweeten 4.1.0 and Windows 10 x64 (build 16299.19).

**Comment by iekozz** [comment]
I also tweeted to @tweetenapp to help raise awareness to this issue. 

Also set-up a brand new virtual machine and the same thing is happening there also.

**Comment by athosbr99** [comment]
Fresh install on FCU. Doesn't have notifications here either.

**Comment by iekozz** [comment]
@d4k0 @athosbr99 I created a bug report in the feedback app from microsoft: https://aka.ms/Uq4r7s - It was working fine before I updated. So I think this is likely a issue with the update. I also got a tweet from @MehediH saying that he does not have time to look into issues like this. 

You can help the feedback by upvoting it. Thanks.

**Comment by d4k0** [comment]
I somehow get "Your Account doesn't have access to this feedback." when clicking on the link.

However, I found a few other reports in the feedback app that say that the mail app doesn't show any notifications anymore. Discord seems to have the same problem: https://www.reddit.com/r/discordapp/comments/779bvl/windows_10_fall_creators_update_broke_popup/

But somehow this doesn't seem to get much attention as I also couldn't find any website or forums where this is discussed :-/.

**Comment by athosbr99** [comment]
The same happened to me. Check if you are logged in the feedback app, I wasnt for some reason

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by d4k0** [comment]
I'm already logged in, but it still doesn't work. It seems that you can only see feedback from your region:

>  Feedback Hub is designed to display the feedback posts only from the region you have selected in your Microsoft account.

Source: https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_security/how-to-change-feedback-hub-region/52978af0-951c-4055-975c-68d837aa24de

When I click on Feedback Hub links from my region (Europe), it works just fine :-/.

**Comment by MehediH** [comment]
Hi everyone, I am investigating this issue and will get back to you guys if I find a fix.

**Comment by iekozz** [comment]
@MehediH Thanks for the update. If you need me (or someone else here) to test some things or to see if it's fixed, let me know.

**Comment by iekozz** [comment]
@MehediH Hi there, is there any news on this issue? Thanks!

**Comment by tekniffen** [comment]
Same issue. Dead notifications since creators update. Tried full reinstall but it didn't fix anything. Notification sound comes through but nothing in Action Center.
