### ISSUE TITLE
[Feature Request] With multiple accounts: Choose which account follows/unfollows

### ISSUE THREAD

**Issue by Duke-Igthorn** [MehediH/Tweeten#34]
So far when having multiple accounts only the first (main) account can follow other users. 
It would be nice to be able to choose which account does the follow/unfollow, similar to the dialogue that allows multiple accounts to send a tweet.

**Comment by MehediH** [comment]
It's already there. Open a profile, click on the more options icon, then click on "Follow from accounts"

**Comment by Duke-Igthorn** [comment]
Ohhhh dang I am stupid! Didn't see that there. Whooops never mind <_<
I'll test it out then, thanks for the heads up! <3
