### ISSUE TITLE
Like button

### ISSUE THREAD

**Issue by ThatsMiguel** [MehediH/Tweeten#36]
This is the like button unpressed
![First Image](https://i.imgur.com/rIS5b20.png)
And this the button after pressed
![Second Image](https://image.prntscr.com/image/YAnOEJ0TRWerq3sljX6RlQ.png)
The button be misaligned

**Comment by MehediH** [comment]
This is a bug in the Chrome version which is no longer supported. Please wait for Tweeten 2 for Chrome.
