### ISSUE TITLE
[BUG] "Minimize to tray on exit" doesn't work

### ISSUE THREAD

**Issue by Tindal** [MehediH/Tweeten#38]
Tweeten Version: 0.1.160425-1600
OS: Windows 7 x64

Issue: The application closes although that option "Minimize to tray on exit" is enabled.

**Comment by MehediH** [comment]
It minimizes to the tray as expected.

**Comment by Tindal** [comment]
Tweeten Version: 0.1.160508-2200
Unfortunately, this feature still doesn't work for me. :(
When i minimize the app - it minimized. But when i close it - it closes and I have to run it again.
