### ISSUE TITLE
Flashing UI when window is maximised

### ISSUE THREAD

**Issue by redking974** [MehediH/Tweeten#39]
Hi @MehediH I have issues with the Tweeten UI. When the window is maximised, the UI flashs all the time and I can't see the popup window (when I click on a pic, when I want to RT) because of these flashes.
If I reduce the size of the window all these UI issues disappears.
I thought about an incompatibility with the resolution of my display (3840x2160). Maybe high resolutions are not been supported.

Regards

**Comment by MehediH** [comment]
Are you on MacOS?

**Comment by redking974** [comment]
Hi @MehediH no I'm on Windows 10 1607.
I don't really know since which version I've got this issue, but about at least a month. Only when windows is maximised (I need to reduce the windows about the half screen to remove this flashing/blinking issue)

**Comment by MehediH** [comment]
Can you please record a video demonstrating the issue?

**Comment by redking974** [comment]
Hi @MehediH, as requested I've uploaded a video when you could see that if I click on a pic or on the RT button, the popup window won't appeared or will be flashing/blinking
https://www.youtube.com/watch?v=x5YZPZPbT1w
Regards.

**Comment by redking974** [comment]
Hi, do you know if I can fix this @MehediH ? Regards

**Comment by MehediH** [comment]
Did you try updating your graphics driver?

**Comment by redking974** [comment]
Hi yes, I already up to date my drivers but the issue remains
