### ISSUE TITLE
Interface issues

### ISSUE THREAD

**Issue by juanscv** [MehediH/Tweeten#4]
- The Mac icon is too big http://take.ms/6k4qh can you make it smaller?

- Verified icon is a bit too low http://take.ms/1PhO3 CSS 'margin-top' is 3px, should be 1px. 

Tweeten 4.0.0
Mac OS Sierra 10.12.5

**Comment by MehediH** [comment]
In what way is the Mac icon too big? Could you expand on that, please?

**Comment by juanscv** [comment]
It's bigger than other round icons and almost overlaps with the 'open app' indicator (see screenshot) http://take.ms/31WK6

**Comment by shanegriffiths** [comment]
I can verify that the Mac dock icon is too large.

![screen shot 2017-06-30 at 18 33 16](https://user-images.githubusercontent.com/652339/27747341-9ae8da2a-5dc2-11e7-9e73-2907dd8d3d47.png)

**Comment by MehediH** [comment]
Any idea what's the actual size of app icons on MacOS?

**Comment by shanegriffiths** [comment]
Hey @MehediH I've just compared the `twitter.icns` file and the Tweeten one. I'm not an expert on MacOS icons but if you copy the Twitter one I'm sure you're not going to go wrong.

Notice how the file is 1024px but they provide a little padding. I think that's what's throwing off the Tweeten icon.

![screen shot 2017-07-01 at 12 16 03](https://user-images.githubusercontent.com/652339/27761595-15f84b8a-5e57-11e7-867f-e9563f43825a.png)

Increase the icon to 1024 and add in 60px padding from the edges. That should improve things.

**Comment by shanegriffiths** [comment]
@MehediH I've been also working on some UI CSS overrides which you may want to look at? I'll share once I've completed it but essentially I feel the UI would look a lot nicer if **ALL** the Uppercase titles and labels were converted to lowercase.

**Comment by MehediH** [comment]
Tweeten follows some of the Microsoft Design Language 2 guidelines where headers are supposed to be all uppercase. I'd still love to take a look at the tweaks though :)

**Comment by MehediH** [comment]
Icon issue fixed on  4.0.2.
