### ISSUE TITLE
@username no propositions

### ISSUE THREAD

**Issue by nykoo** [MehediH/Tweeten#41]
Hi,

First of thank you for this great application.

I've got a problem in Tweeten (and even in twitter web), when i begin to type an @username i'd normaly have suggestions and auto-completion... But this is not working anymore :/ and this is a big problem as i don"t know exactly @username of following and followers...

Do you have and idea, where the problem come from ?

Thank you for your help

**Comment by MehediH** [comment]
This is a TweetDeck issue.
