### ISSUE TITLE
Used to be able to scroll to RT popup on smaller windows; no longer doable with latest update

### ISSUE THREAD

**Issue by jtabangcura** [MehediH/Tweeten#43]
Hi! I use Tweeten primarily so I can access multiple accounts at once and also RT to them--it's become very useful! However, a complaint I do have about Tweeten is the RT popup:

I like to keep Tweeten narrowed to display just one column at a time and when I first started using this app, the popup remained static and I would need to expand the window to full width to see it. About a year ago(?) an update "fixed" this and instead of expanding, I could just scroll down/right to access the popup. But the latest update reversed that and now I have to expand the window again!

I don't know if this is how the function was intended, but it would be really nice if the RT popup could be responsive to accommodate smaller windows. I haven't tried "hacking" Tweeten via the custom CSS feature, but I guess I could also try tinkering with it a bit as a temporary solution...

Anyway, thanks for all you've done so far and for looking into this! This is the best desktop Twitter app I've tried so far.

PS: if it helps, I am using Tweeten on macOS Sierra 10.12.5

**Comment by MehediH** [comment]
I will bring back support for narrow windows in the future, thanks
