### ISSUE TITLE
Text Color in dark mode same as background colour

### ISSUE THREAD

**Issue by amanaryan** [MehediH/Tweeten#44]
Hi,

On MacOS, In dark mode, if I type anything in the search box, Initially the text color is same as the background color, making the text invisible. Only after the focus shifts outside the box, the text color changes to a light color making it visible. 

So when the user is typing something in the search bar, the text is invisible.

Here is a screen recording to make things more clear : [tweeten.zip](https://github.com/MehediH/Tweeten/files/1524481/tweeten.zip)

**Comment by aaronosher** [comment]
It also happens in the "Accounts you can act as" part of the accounts screen when in dark mode.

**Comment by MehediH** [comment]
@aaronosher Please provide a screenshot

@amanaryan Should be fixed in the next update, thanks!

**Comment by aaronosher** [comment]
Seems to have resolved itself perhaps it's an issue immediatley after adding a new account.
