### ISSUE TITLE
Acounts you can act as card is too wide for accounts drawer

### ISSUE THREAD

**Issue by aaronosher** [MehediH/Tweeten#46]
The "Accounts you can act as card" is physically wider than the rest of the cards in the accounts drawer. The drawer itself is also too small as it causes the "Link Another account you own" to cross two lines.

**Comment by MehediH** [comment]
Sorry, what's the issue here? Can you provide some screenshots?

**Comment by aaronosher** [comment]
<img width="1409" alt="screen shot 2017-12-22 at 23 15 42" src="https://user-images.githubusercontent.com/4386583/34314678-32a774fe-e76e-11e7-8c85-a1abf2138675.png">
See bottom left

**Comment by MehediH** [comment]
Fixed
