### ISSUE TITLE
Settings Improvements

### ISSUE THREAD

**Issue by pixeldesu** [MehediH/Tweeten#47]
Tweeten is at the moment saving user preferences into the application state. If someone is using both TweetDeck and Tweeten this will always cause Tweeten to revert settings back.

You're doing this so you can access settings outside of the TweetDeck-scope, since you open a seperate window for settings.

Consider using something like the provided Electron IPC to send the settings around if required, so you don't have to save them locally.

**Comment by MehediH** [comment]
Need a bit of detail here, Andreas. I assume you want Tweeten to change the settings on TweetDeck in real-time and set the customizations based on settings stored on TweetDeck instead of the local app data?

_Tweeten already leverages Electron's IPC to communicate between different processes, by the way._

**Comment by pixeldesu** [comment]
What I mean is the following:

You are saving a shallow copy of TweetDeck settings into the own application store `store.get('TD.settings.*')`. If settings are changed outside of Tweeten, Tweeten will reapply the settings it saved last on a new startup.

You can always get all settings from TweetDeck (either through the functions in `TD.settings` or the client storage in `TD.storage`), so instead of saving your own copy of the settings, only apply your required/recommended settings and then try to keep as much as possible in the hands of TweetDeck!

I meant using the IPC in a way so that you can pass the current settings values from one window to another. I know Tweeten already utilizes IPC! Using IPC for this wouldn't require saving them to the store and then retrieving them again!

Real-time is also not too much of an issue since you can simply trigger the event [`dataSettings`](https://github.com/DeckHack/discoveries/blob/master/docs/settings.md#usage) to update settings for the current session.

**Comment by MehediH** [comment]
Yep, that's exactly what I am planning on adding with 4.4 or 4.5.

**Comment by MehediH** [comment]
Fixed https://github.com/MehediH/Tweeten/releases/tag/4.3.1
