### ISSUE TITLE
Spell checker not working [Windows version]

### ISSUE THREAD

**Issue by Zignd** [MehediH/Tweeten#48]
After enabling the spellchecker, right click > Settings > Enable spell checker, every word you type gets decorated with that red line, I tried writing sentences in Portuguese and English, but I still ended up with this red line. Also, it'd be nice to have an option that would allow you to choose a specific language for the spell checker.

**Comment by MehediH** [comment]
Spell checker only works with English and your system's language needs to be set to English for the spell checker to work properly.
