### ISSUE TITLE
Allow Users to keep their own Settings

### ISSUE THREAD

**Issue by pixeldesu** [MehediH/Tweeten#48]
On first/every startup Tweeten is setting the users theme to be dark and font size to be large.

Instead of doing this, leave the users setting as is and maybe open a modal saying that you have recommended settings (dark theme + bigger font) and allow users setting it that way.

Having my settings changed by Tweeten is not what I really want.

**Comment by MehediH** [comment]
Each application has its own default settings for certain things. While I understand you may not want your TweetDeck settings being overwritten by us, Tweeten is still going to apply the recommended options that work best for the design of the app.

But I do agree with showing a warning about the recommended settings -- will look into adding this for new users during the onboarding experience.

**Comment by MehediH** [comment]
Fixed https://github.com/MehediH/Tweeten/releases/tag/4.3.1
