### ISSUE TITLE
Javascript error with v 2.0

### ISSUE THREAD

**Issue by razgriz417** [MehediH/Tweeten#49]
Hi,
After updating to 2.0, I'm no longer able to load Tweeten on PC (w8.1 x64) I get this error everytime I try. I've tried uninstalling and reinstalling java as well as Tweeten to no avail :( Any ideas?
![tweeten error](https://cloud.githubusercontent.com/assets/19318733/15203365/d507dcb2-17d0-11e6-8b1d-acfd157a129b.PNG)

**Comment by MehediH** [comment]
Delete the Tweeten folder from %appdata% and then reopen the app.
