### ISSUE TITLE
Add Account feature missing

### ISSUE THREAD

**Issue by AfonsoGomes** [MehediH/Tweeten#55]
I know there is an issue #31, [commented on it](https://github.com/MehediH/Tweeten/issues/31#issuecomment-356234736), with this and apparently fixed, but it doesn't seem to be working for me.

It is happening exactly the same as what's been reported in that issue.

Version: 4.3.1
Windows 10 Fall Creators Update - both Microsoft Store and 64-bit downloaded version

**Comment by MehediH** [comment]
I just checked and the feature is working just fine for me. You need to click on "Click another account you own", login, and then restart the app. Open Accounts, go into Team Invitations and accept the invite for the account you just added. 

![image](https://user-images.githubusercontent.com/10274434/35165371-067a8158-fd46-11e7-8e74-7205c6c54068.png)

**Comment by AfonsoGomes** [comment]
Isn't this to add another member to use the same account? What I intended was to get two accounts and switch between them, similar to the android twitter app.

**Comment by freeassociates** [comment]
Tweeten is a nice app, but I find I (too) can no longer add an account.  I just installed the latest Mac version (4.6.1) from your site. I clicked the Accounts icon at bottom left. I see a team account and a related personal account. Need to add another, but can't find where or how to do that. Please help! Thanks.

**Comment by joelgratcyk** [comment]
Same issue here. I don't want to add accounts to a team to tweet from one account. I want multiple accounts to be used and tweeted from within the app. Looking to schedule content and can only do that with one main account. Just installed the latest Tweeten app and am running the latest MacOS.
