### ISSUE TITLE
Tweeten 4.3 to 4.3.2 loops as login page on Windows 8.1

### ISSUE THREAD

**Issue by FleuryK** [MehediH/Tweeten#59]
Hello.

First of all, congratulations on your software which takes a lot of your free time.

I have Windows 8.1 x64 installed on my PC.

But ... Versions 4.3 to 4.3.2 loops as login page. After login, your software closes and reopens and I go back to the login page. Impossible to go further.

For the moment, I am obliged to content myself with your version 4.2.2 which it has no problem.

Can you fix it/fix this problem?

Sincerely.

**Comment by patricktokeeffe** [comment]
I confirm identical behavior on Win7 Pro SP1 x64 using 4.3, 4.3.1 and 4.3.2. After pressing 'Get started' the application (presumably) crashes and restarts. However, 4.2.2 launches correctly.

fwiw Tweeten doesn't show up as an authorized app in Twitter settings

**Comment by MehediH** [comment]
Please try with 4.3.3.

**Comment by patricktokeeffe** [comment]
:+1: I was able to run 4.3.3 sucessfully

**Comment by FleuryK** [comment]
I have reopen this issue because version 4.3.3 won't fix this bug.
He loops again as login page. After login, he closes and reopens and I go back to the login page. Impossible to go further.
