### ISSUE TITLE
Close to system tray feature

### ISSUE THREAD

**Issue by wimg** [MehediH/Tweeten#6]
A 'close to system tray' feature would be nice (like Tweetdeck for Windows), allowing the app to sit in the system tray when clicking the X or pressing ALT+F4.

**Comment by MehediH** [comment]
Added with Tweeten 1.8!

Windows: tweeten.xyz/windows
OS X: tweeten.xyz/osx

**Comment by wimg** [comment]
I'm guessing that version is not downloadable yet ?

**Comment by MehediH** [comment]
It is: http://tweeten.xyz/windows

**Comment by wimg** [comment]
Tried it, as soon as I click the X to close, it's gone completely...

**Comment by MehediH** [comment]
Right click anywhere in the app then click on minimise to tray.

**Comment by wimg** [comment]
Any option to minimize to the system tray instead of the task bar ?

**Comment by wimg** [comment]
Ah sorry there is an option for that... I missed the one. A shortcut would be nice though ;-)
Thanks !
