### ISSUE TITLE
Unable to login (macOS High Sierra 10.13.3)

### ISSUE THREAD

**Issue by TheRayJohnson** [MehediH/Tweeten#63]
Hi Guys!

Just found Tweeten while searching Twitter clients on Google, downloaded for Mac but cannot login?

a. Downloaded and installed;
b. LOGIN on welcome screen via the popup (which i'm guessing is twitter.com) - width is broken? fine if you submit fake login.
c. "GET STARTED" closes Tweenten then relaunches itself to login again and repeats.

Tweeten 4.3.2
macOS High Sierra 10.13.3

**Comment by MehediH** [comment]
Please try with 4.3.3.

**Comment by holgr** [comment]
I'm seeing the same login issue using 4.3.3, but I'm on the macOS 10.13.4 Beta (currently Build 17E150g), so it's very possible that this is completely my fault :)
