### ISSUE TITLE
Get kicked back to login screen after clicking Ge

### ISSUE THREAD

**Issue by laurin1** [MehediH/Tweeten#65]
- New Tweeten user 
- Windows x64
- 4.3.3

After entering Twitter username and password, then getting 2-factor screen, I enter the code, then go to the GET STARTED / CHANGE SETTINGS screen. I click GET STARTED and am kicked back to the login screen.

**Comment by nicooprat** [comment]
Same here on Mac 10.12.6. App restarts when logged in. Can't move itself to applications folder neither.

**Comment by SanderGit** [comment]
Same here on macOS. Moved app to Applications but kicked back to login screen after entering 2FA code.

**Comment by dnlx** [comment]
same here on Windows 10.

**Comment by albertsj1** [comment]
4.3.4 was quietly released a few hours ago and I can confirm it fixed this issue for me.
