### ISSUE TITLE
Recommendations for this repo and website

### ISSUE THREAD

**Issue by albertsj1** [MehediH/Tweeten#68]
Sorry, but I wasn't sure where else to put something like this.

I just ran across Tweeten last week and it's pretty awesome.  Thank you for spending your time to work on this.  I do have some suggestions.

1. Add a link to the official [Tweetenapp](http://tweetenapp.com) website in the Github description.
2. Add a `README.md` to this project so people know what it is and how it relates to tweetenapp.com.  Even just a very short README would be helpful to new users trying to understand what this repo is.
3. Add a link on the official [Tweetenapp](http://tweetenapp.com) website to this Github repo.  This let's user's know it's an open source project.  This simple fact means a lot to quite a few people.

Thanks again for your work on this project.

**Comment by MehediH** [comment]
Hi, this repo is just for the website and the application isn't open sourced.
