### ISSUE TITLE
Column width doesn't work in Windows 7 64-bit app

### ISSUE THREAD

**Issue by RheingoldRiver** [MehediH/Tweeten#7]
I have the narrowest column width selected but my columns aren't actually getting any narrower, it's just that the size of the media changes a bit.

**Comment by gus33000** [comment]
Are you using the slider in tweeten settings or the TD's setting panel? The plan is to remove the TD settings panel in the future and redirect everything to the tweeten settings. To properly change the column width you need to change it in the tweeten settings, which you can access by pressing alt, clicking on tweeten in the menu bar then settings. Be sure to tell us if  this worked so we can close this issue.

**Comment by RheingoldRiver** [comment]
Yeah I was using the wrong panel, found the right one, thanks. However, the min. width is still wider than I had my columns in TweetDeck so if possible I'd like to have them go to about 33% narrower. Thanks for the reply!
