### ISSUE TITLE
Scroll bar acts weird

### ISSUE THREAD

**Issue by ashleythedragon** [MehediH/Tweeten#70]
Hello. New user on Tweeten. Using Windows 10 app. Sometimes ( more times than not) the scroll bar goes crazy and follows the cursor mouse if I move it. Also, if I double click on any scroll bar ( horizontal or vertical), the settings screen pops up. It is very disruptive to use Tweeten when you cant move the mouse without the columns scroll going crazy or trying to scroll manually dragging the scrollbar like it has always been done and the settings window popping up. I can provide a video of it. I'm not keeping the mouse buttons pressed, it happens by itself, also only on tweeten ( so not my PC or mouse being funny)

You can see the video here ( but for some reason the cursor is invisible. Recording software shenanigans)

https://www.youtube.com/watch?v=oD2ySOnb4xQ

**Comment by MehediH** [comment]
That's very weird. Have you tried uninstalling/reinstalling Tweeten? Also, does it happen on tweetdeck.twitter.com?

**Comment by ashleythedragon** [comment]
Yes, I tried uninstalling and reinstailling, also using the PC 64bits version instead of the Windows 10 app, it still happens the same ( although it is less common). Been using Tweetdeck all day today and it didn't.

**Comment by ngdio** [comment]
I have the exact same issue at the moment. Windows 10 v1809, Windows Store version. Think it might have happened on my Mac too, but I'm not sure since I use the touchpad to scroll.
