### ISSUE TITLE
Shift + mouse wheel doesn't scroll horizontally anymore

### ISSUE THREAD

**Issue by matteocontrini** [MehediH/Tweeten#8]
After 2.0, I'm not able to scroll horizontally with shift + mouse scrolling anymore. I remember it was working before, but I've also noticed that I'm having the same issue in TweetDeck, so it might be a recent Twitter change.

It appears that the shortcut only works when the mouse is hovering the headers at the top ("home", "notifications", etc.)

**Comment by MehediH** [comment]
Seems like a TweetDeck issue
