### ISSUE TITLE
Emoji Picker - Emojis not loaded or broken

### ISSUE THREAD

**Issue by Thund3rst0rm** [MehediH/Tweeten#82]
Emojis are not displayed correctly. Tweeten Version 4.4.0 for Windows (64-bit) [TweetenSetup.exe]
![broken](https://user-images.githubusercontent.com/39056787/39760641-274871ca-52d6-11e8-891f-a6082d41c2b5.PNG)

**Comment by MehediH** [comment]
please update windows
