### ISSUE TITLE
Right click menus

### ISSUE THREAD

**Issue by Stanzilla** [MehediH/Tweeten#83]
Currently when you right click anywhere, the same popup comes up

![tweeten_2018-05-09_14-19-41](https://user-images.githubusercontent.com/75278/39814295-0cce2786-5394-11e8-9244-1bcd2519c7e8.png)

All actions under "Edit" do not work. I sort of expected that for most, but not "Copy". That should work at least. 

One idea would be to just open the "..." menu when you right click a tweet, since that has all the useful actions:

![tweeten_2018-05-09_14-21-12](https://user-images.githubusercontent.com/75278/39814392-5b07ef68-5394-11e8-89c7-73fba63cc608.png)

**Comment by MehediH** [comment]
As discussed, this will be way too complex to implement and there are a lot of other UX complications.
