### ISSUE TITLE
Unable to open app

### ISSUE THREAD

**Issue by jgsiegel** [MehediH/Tweeten#84]
When I open the app, it stays at the loading screen indefinitely, with the three dots going back and forth and the message giving me the link to this github to submit a bug report. Not sure if there's a place to pull an error report or anything like that built into the app.

I uninstalled and reinstalled the application as well and that didn't work. I'm working on a Windows computer and the application is the 64-bit Windows version.

**Comment by richardjohn** [comment]
Having the same problem on OS X

**Comment by DioBrando141** [comment]
having the same issue. W10 and 64bit

**Comment by MechaGS** [comment]
Same problem also. W10 and 64bit

**Comment by MehediH** [comment]
Fix for the new update is now out. You can get it from tweetenapp.com
