### ISSUE TITLE
Tweeten not opening properly

### ISSUE THREAD

**Issue by agentblue2** [MehediH/Tweeten#85]
![screenshot 22](https://user-images.githubusercontent.com/22734968/40088179-20d626f6-5863-11e8-8746-b95b63b62561.png)
 Tweeten stuck on splash screen upon opening - application has been re-installed - current issue persists

**Comment by RalphyLikes** [comment]
Me too... ಥ_ಥ

**Comment by daruyanagi** [comment]
Me too... 😿

**Comment by Technomax7** [comment]
Me too!

**Comment by MehediH** [comment]
Guys download the new update, 4.4.1 from the tweeten website or GitHub releases.
