### ISSUE TITLE
Can't log in on Windows 10 x64 Pro, Surface Pro 3.

### ISSUE THREAD

**Issue by RupertMichaelBear** [MehediH/Tweeten#88]
Asks for twitter log in then just says it's taking along time to log in and hangs.

**Comment by BradSmith1985** [comment]
Same problem here, Win10 x64 Enterprise.

**Comment by MHerbst** [comment]
I had the same problem but with the latest update from the Windows Store ist worked again.

**Comment by gustavoeb** [comment]
same. used to work, now it doesn't

**Comment by MehediH** [comment]
https://twitter.com/TweetenApp/status/996861300780294145

If the update isn't available, just download the win32 app for faster updates
