### ISSUE TITLE
How do you build Tweeten?

### ISSUE THREAD

**Issue by axfelix** [MehediH/Tweeten#89]
I'd like to take a shot on building this on Linux now that the new Twitter API changes are officially happening for August and my beloved https://github.com/baedert/corebird is going to die, I need a new desktop client...

I don't h ave too much Electron experience but I'd love to try this out.

**Comment by MehediH** [comment]
Tweeten is actually a pretty complicated app. I have been thinking of bringing Tweeten to Linux but the only major hurdle right now is implementing the auto-updating system for the app on Linux. If you have any suggestions on that, please feel free to share your ideas :)

**Comment by MehediH** [comment]
No, it's more than just CSS and JS files

**Comment by axfelix** [comment]
Yeah, Linux is really good at package managers, not so good at auto-updating. If we don't get that feature, that's OK -- I'm just really keen to have a replacement by the time Corebird stops working in August due to the API changes, since you're already the only good app (imo) on Windows and that's the only good one on Linux!

**Comment by MehediH** [comment]
I guess we could distribute it through package managers and let people update via there?

**Comment by axfelix** [comment]
Yup! Just build a snap/deb/rpm every so often and that'll do

**Comment by MehediH** [comment]
I assume it's safe to say Snap is the best way to go for this?

**Comment by axfelix** [comment]
I've still never used them, I'm much more used to debs and rpms and arch packages, but if you don't normally do Linux stuff and it seems like a simpler solution to you, go for it, I gather that's what the format is for.

**Comment by axfelix** [comment]
Seems like `npm run release` tends to generate both snap and AppImage, actually, which should work fine; I just had to build another app. In case you're curious.

**Comment by MehediH** [comment]
Well, right now, I am dealing with simple issues. The app gets stuck when the first WebView is loaded, so I don't know what's wrong with it.

**Comment by axfelix** [comment]
Let me know if you want me to try to test a build with verbose logging or anything like that, only about six weeks now until the API changes :(

**Comment by MehediH** [comment]
Do you have Skype or Discord?

**Comment by axfelix** [comment]
sure, `axfelix-` on Skype
