### ISSUE TITLE
Missing blur on direct messages

### ISSUE THREAD

**Issue by catlinman** [MehediH/Tweeten#92]
Hey there!

As the title says I am missing the blur on the direct messages column even with the setting turned on. Been experiencing this issue for about a month now and it doesn't seem to be working any time soon. I've already tried a few things in fixing the issue but to no avail.

- Disabled the setting, restarted Tweeten and then re-enabled the setting.
- Logging out and back in, additionally removed message columns and then added them again.
- Uninstalled Tweeten and removed all files associated with it. Reinstalled and everything was the same.

It would be great to have this feature back since I work in an open environment and would like to have a bit of privacy when it comes to the messages of some of my clients and friends. Really loved the feature coming into Tweeten and would like to use it again! Thanks in advance!

**Comment by fuyutsuki** [comment]
I have the same issue! please fix this!

**Comment by MehediH** [comment]
Will be fixed soon.
