### ISSUE TITLE
Single instance mode taskbar issues & pop out columns suggestion

### ISSUE THREAD

**Issue by catlinman** [MehediH/Tweeten#94]
Hey! Somewhat reviving an [old issue mentioned here](https://github.com/MehediH/TweetenSite/issues/68) since it's still an annoyance.

To quote the original issue by @EmuAGR:

> I have Tweeten pinned to my taskbar so the Window opens next to my browser. [...] when I want to restore it through my pinned icon, a second instance of Tweeten is launched instead of the old one.

>Since Tweeten allows the usage of multiple accounts, I think instances should be limited to one (via checkbox or by default).

I find that this should be default behavior as well, since it's somewhat obscure that you have to enable the minimize to tray feature to do this. It makes pinning Tweeten to the taskbar impossible otherwise, as it always creates new instances that do not stack with the shortcut placed. For new users that do not know about this, it could pose a major inconvenience when it comes to setting up the application.

Even without minimizing, it should be limited to one instance unless further tweaking is used, since most users will not need more than one instance and even so: Shouldn't those instances be selectable and configurable then? The whole multiple instance thing just doesn't have too many practical uses I believe. Especially considering that Tweeten has support for multiple accounts.

If anything at all there should be a way to pop out columns from the timeline. This would make the whole instance issue redundant and create some new and useful use cases for the application as a whole. People wanting to use Tweeten as a dashboard on a big screen can selectively move columns to a different window of Tweeten while it still running under one whole instance.

**Comment by catlinman** [comment]
Since I see no changes here I am going to switch off Tweeten since it's a breaking feature for me as it will simply duplicate itself on my taskbar and I can't pin nor get it to stick to the instance I opened it with which to me is quite breaking and annoying. I have a rather loaded taskbar where I want my icons to remain in one position for fast and easy access and having Tweeten open itself multiple times just doesn't work with that.

![nvidia share_2018-06-15_09-20-47](https://user-images.githubusercontent.com/1859270/41455431-70f3364c-707d-11e8-9843-64af6a0bc32f.png)

**Comment by MehediH** [comment]
Tweeten will be single instance by default with 4.5.
