### ISSUE TITLE
Enhancement: One-click copy link to clipboard?

### ISSUE THREAD

**Issue by KaranParmar** [MehediH/Tweeten#98]
One feature that would be nice to add in the next update is a one-click copy link to clipboard. 

Currently, it requires two clicks: 
1. Right-click on time of the tweet 
2. Then click on 'Copy link to clipboard'

Or, three clicks:
1. Click on hamburger menu icon
2. Then click on 'Copy link to clipboard'
3. Then click on 'Copy Link'

As someone who copies and pastes the link of tweets frequently, this would make it easier to have a simple feature which would be very effective. 

I was thinking maybe a one-click copy link icon placed on each tweet, where you click on it, it would automatically copy the link to the clipboard.

**Comment by MehediH** [comment]
Doesn't make sense, would clutter the UI
